- terasoluna-gfw-parent/pom.xml
> Update Spring version to 3.2.13 #197

- terasoluna-gfw-parent/pom.xml
@btshimizukza 
Forgot to add `org.terasoluna.gfw:terasoluna-gfw-jodatime` in terasoluna-gfw-parent
#224
> add org.terasoluna.gfw:terasoluna-gfw-jodatime in terasoluna-gfw-parent #224

- .travis.yml
> add org.terasoluna.gfw:terasoluna-gfw-jodatime to .travis.yml #224

- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/pagination/PaginationInfo.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/pagination/PaginationTag.java
- terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/pagination/PaginationTagTest.java
please merge with master if all OK. branch tested on jenkins. #13 #14
> changes related to Issues/13 Issues/14

- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/query/LikeConditionEscape.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/query/QueryEscapeUtils.java
- terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/query/QueryEscapeUtilsTest.java
> separate functionalities to escape full-witdh wildcards or not #78

- terasoluna-gfw-web/src/main/resources/META-INF/terasoluna.tld
＃239
added enableLinkOfCurrentPage in terasoluna.tld
> added enableLinkOfCurrentPage in terasoluna.tld #239

- terasoluna-gfw-mybatis2/pom.xml
> add orm-ibatis #132

- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/date/DateConvertUtils.java
> remove wrong @since #242

- terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/EnumCodeList.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/message/ResultMessages.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/message/StandardResultMessageType.java
- terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-jpa/pom.xml
- terasoluna-gfw-mybatis2/pom.xml
- terasoluna-gfw-mybatis3/pom.xml
- terasoluna-gfw-parent/pom.xml
- terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-security-core/pom.xml
- terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-web/pom.xml
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/message/MessagesPanelTag.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/pagination/PaginationTag.java
- terasoluna-gfw-web/src/main/resources/META-INF/terasoluna.tld
> revesion 1.1.0 -> 5.0.0

- terasoluna-gfw-parent/pom.xml
> Applied the Spring IO Platform 1.1.1.RELEASE. #205

- terasoluna-gfw-mybatis2/pom.xml
> update orm-ibatis #205

- terasoluna-gfw-jodatime/src/main/java/org/terasoluna/gfw/common/date/AbstractDateFactory.java
- terasoluna-gfw-jodatime/src/main/java/org/terasoluna/gfw/common/date/DateFactory.java
- terasoluna-gfw-jodatime/src/main/java/org/terasoluna/gfw/common/date/DefaultDateFactory.java
- terasoluna-gfw-jodatime/src/main/java/org/terasoluna/gfw/common/date/JdbcAdjustedDateFactory.java
- terasoluna-gfw-jodatime/src/main/java/org/terasoluna/gfw/common/date/JdbcFixedDateFactory.java
- terasoluna-gfw-jodatime/src/main/java/org/terasoluna/gfw/common/date/jodatime/JdbcFixedJodaTimeDateFactory.java
#252 
resolved sonar issues in terasoluna-gfw-jodatime project
> resolved sonar issues in terasoluna-gfw-jodatime project #252

- terasoluna-gfw-common/pom.xml
- terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-parent/pom.xml
- terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-web/pom.xml
> polished pom.xml #254

- terasoluna-gfw-mybatis3/pom.xml
- terasoluna-gfw-parent/pom.xml
> moved dependency managements about mybatis3 to teraoluna-parent/pom.xml .#260

- terasoluna-gfw-mybatis3/pom.xml
- terasoluna-gfw-parent/pom.xml
please review #260
see https://github.com/terasolunaorg/terasoluna-gfw/issues/260#issuecomment-72780606
> moved dependency on mybatis3 #260

- terasoluna-gfw-common/pom.xml
- terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-jpa/pom.xml
- terasoluna-gfw-mybatis2/pom.xml
- terasoluna-gfw-mybatis3/pom.xml
- terasoluna-gfw-parent/pom.xml
- terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-security-core/pom.xml
- terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-web/pom.xml
> Change framework name & modify some description in pom.xml. #265

- terasoluna-gfw-common/pom.xml
- terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-parent/pom.xml
- terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-web/pom.xml
> Import the Spring IO Platform. #267

- terasoluna-gfw-common/pom.xml
- terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-jpa/pom.xml
- terasoluna-gfw-mybatis2/pom.xml
- terasoluna-gfw-mybatis3/pom.xml
- terasoluna-gfw-parent/pom.xml
- terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-security-core/pom.xml
- terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-web/pom.xml
> Upgrade Version to 5.1.0-SNAPSHOT. #270

- terasoluna-gfw-common/pom.xml
- terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-jpa/pom.xml
- terasoluna-gfw-mybatis2/pom.xml
- terasoluna-gfw-mybatis3/pom.xml
- terasoluna-gfw-parent/pom.xml
- terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-security-core/pom.xml
- terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-web/pom.xml
> Upgrade Version to 5.0.1-SNAPSHOT. #271

- terasoluna-gfw-common/pom.xml
- terasoluna-gfw-jpa/pom.xml
- terasoluna-gfw-mybatis2/pom.xml
- terasoluna-gfw-parent/pom.xml
- terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-security-core/pom.xml
- terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-web/pom.xml
> Upgrade Version to 1.0.3-SNAPSHOT. #272

- README.md
> fix typo #283

- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/ExistInCodeList.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/NumberRangeCodeList.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/i18n/SimpleI18nCodeList.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/exception/DefaultExceptionLevelResolver.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/exception/ExceptionLevel.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/exception/ExceptionLogger.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/exception/ResultMessagesLoggingInterceptor.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/exception/SimpleMappingExceptionCodeResolver.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/message/ResultMessage.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/query/LikeConditionEscape.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/query/QueryEscapeUtils.java
- terasoluna-gfw-security-web/src/main/java/org/terasoluna/gfw/security/web/logging/UserIdMDCPutFilter.java
- terasoluna-gfw-security-web/src/main/java/org/terasoluna/gfw/security/web/redirect/RedirectAuthenticationHandler.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/codelist/CodeListInterceptor.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/el/Functions.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/exception/ExceptionLoggingFilter.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/exception/HandlerExceptionResolverLoggingInterceptor.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/logging/mdc/XTrackMDCPutFilter.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/message/MessagesPanelTag.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/mvc/support/CompositeRequestDataValueProcessor.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/mvc/support/RequestDataValueProcessorAdaptor.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/pagination/PaginationInfo.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/TokenStringGenerator.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenInterceptor.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/util/ResponseUtils.java
Please review #276 .
Build is successful using the Oracle JDK8(on [travis](https://travis-ci.org/terasolunaorg/terasoluna-gfw/builds/53538832)).
This PR resolved errors only.
Warnings resolve by other issue(#277).
> #276: Modify JavaDoc errors on JDK8

- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/ExistInCodeList.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/NumberRangeCodeList.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/i18n/SimpleI18nCodeList.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/exception/DefaultExceptionLevelResolver.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/exception/ExceptionLevel.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/exception/ExceptionLogger.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/exception/ResultMessagesLoggingInterceptor.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/exception/SimpleMappingExceptionCodeResolver.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/message/ResultMessage.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/query/LikeConditionEscape.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/query/QueryEscapeUtils.java
- terasoluna-gfw-security-web/src/main/java/org/terasoluna/gfw/security/web/logging/UserIdMDCPutFilter.java
- terasoluna-gfw-security-web/src/main/java/org/terasoluna/gfw/security/web/redirect/RedirectAuthenticationHandler.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/codelist/CodeListInterceptor.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/el/Functions.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/exception/ExceptionLoggingFilter.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/exception/HandlerExceptionResolverLoggingInterceptor.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/logging/mdc/XTrackMDCPutFilter.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/message/MessagesPanelTag.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/mvc/support/CompositeRequestDataValueProcessor.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/mvc/support/RequestDataValueProcessorAdaptor.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/pagination/PaginationInfo.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/TokenStringGenerator.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenInterceptor.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/util/ResponseUtils.java
(cherry picked from commit dc180860e0ab413681b005dac83d2dd00023a94b)
Please review #276 .
**Note:**
The Travis CI using the Oracle JDK8 has been succeed.
For detail, please refer to https://travis-ci.org/terasolunaorg/terasoluna-gfw/jobs/62711810 .
> [5.0.x] #276: Modify JavaDoc errors on JDK8

- .travis.yml
> #290: Support Oracle JDK8 as new build environment on travis

- CONTRIBUTING.md
> add CONTRIBUTING.md #282

- CONTRIBUTING.md
- README.md
I improved a contributing guideline.
Please review improvements of #282 .
> #282: Improve a contributing guideline

- CONTRIBUTING.md
- README.md
(cherry picked from commit 57bcc5a99a03dd90c4a7e642382e798a10e923ce)
Please review #282 .
> [5.0.x] #282: Improve a contributing guideline

- README.md
> #301: Add the <version> tag in README.md

- README.md
(cherry picked from commit 53560988d253ddf20aab86a78b575fe3baa28e0d)
Please review #301 .
> [5.0.x] #301: Add the <version> tag in README.md

- README.md
> [1.0.x] #301: Add the <version> tag in README.md

- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/date/DateConvertUtils.java
> #310: Fix typo in private constant of DateConvertUtils

- README.md
(cherry picked from commit 1fceb4d82ac2fc9fcc42337c26c82cdd7a442402)
Please review #283 .
> [5.0.x] fix typo #283

- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/date/DateConvertUtils.java
- terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/date/DateConvertUtilsTest.java
> #228: fix typo of exception message in DateConvertUtils

- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/JdbcCodeList.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/NumberRangeCodeList.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/ReadWriteLockMapWrapper.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/validator/AbstractExistInCodeListValidator.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/exception/ResultMessagesLoggingInterceptor.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/message/ResultMessage.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/message/ResultMessageUtils.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/message/ResultMessages.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/query/LikeConditionEscape.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/sequencer/JdbcSequencer.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/sequencer/Sequencer.java
- terasoluna-gfw-jodatime/src/main/java/org/terasoluna/gfw/common/date/jodatime/JdbcAdjustedJodaTimeDateFactory.java
- terasoluna-gfw-security-web/src/main/java/org/terasoluna/gfw/security/web/redirect/RedirectAuthenticationHandler.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/el/Functions.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/exception/ExceptionLoggingFilter.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/exception/HandlerExceptionResolverLoggingInterceptor.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/logging/mdc/AbstractMDCPutFilter.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/message/MessagesPanelTag.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/mvc/support/CompositeRequestDataValueProcessor.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/mvc/support/RequestDataValueProcessorAdaptor.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/pagination/PaginationInfo.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/pagination/PaginationTag.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionToken.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenCheck.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenContext.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenContextImpl.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenInfoStore.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/util/RequestUtils.java
Please review #277 .
I confirmed on Oracle JDK 1.8.0_45 and Oracle JDK 1.7.0_80.
> #277: Fix javadoc waringins

- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/date/JdbcAdjustedDateFactory.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/mvc/support/CompositeRequestDataValueProcessor.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/mvc/support/RequestDataValueProcessorAdaptor.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/pagination/PaginationTag.java
#277 additional modification for 1.0.x
> Issues/277 javadoc warngin on jdk8 1.0.x

- terasoluna-gfw-parent/pom.xml
> upgrade spring version(3.2.14). #316

- terasoluna-gfw-parent/pom.xml
> #280: Update the selenium version to 2.46.0

- terasoluna-gfw-parent/pom.xml
(cherry picked from commit 6d071409cfdef290efb2854b8d377a9c8db2ead3)
Please review #280 .
> [5.0.x] #280: Update the selenium version to 2.46.0

- terasoluna-gfw-parent/pom.xml
(backport by manually)
Please review #280 .
> [1.0.x] #280: Update the selenium version to 2.46.0

- terasoluna-gfw-web/pom.xml
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/el/Functions.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/el/ObjectToMapConverter.java
- terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/el/FunctionsTest.java
- terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/el/ObjectToMapConverterTest.java
#297 please review
(squashed https://github.com/terasolunaorg/terasoluna-gfw/tree/issues/297_fix-fquery)
> Support nested fields in f:query #297

- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/message/MessagesPanelTag.java
> #264: fix typo in javadoc of MessagesPanelTag

- terasoluna-gfw-web/pom.xml
- terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenTagTest.java
> #329: Change JSTL artifact (javax.servlet:jstl -> org.apache.taglibs:taglibs-standard-jstlel)

- terasoluna-gfw-parent/pom.xml
- terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/pagination/PaginationInfoTest.java
I've backported to 5.0.x.
Please review #315 .
> [5.0.x] #315: Update to Spring IO Platform 1.1.3

- terasoluna-gfw-web/pom.xml
- terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenTagTest.java
I've backported to 5.0.x.
Please review #329 .
> [5.0.x] #329: Change JSTL artifact (javax.servlet:jstl -> org.apache.taglibs:taglibs-standard-jstlel)

- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/el/ObjectToMapConverter.java
- terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/el/FunctionsTest.java
- terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/el/ObjectToMapConverterTest.java
I've fixed bug about null property using reset mechanism provided by Spring Web MVC.
> #297: Modify to show reset parameter that start with '_', if value is null

- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/el/ObjectToMapConverter.java
- terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/el/FunctionsTest.java
- terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/el/ObjectToMapConverterTest.java
(cherry picked from commit b2d5f7a857f0fb59c85b2ce580cfecde1703d09b)
> [5.0.x] #297: Modify to show reset parameter that start with '_', if value is null

- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/el/ObjectToMapConverter.java
- terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/el/ObjectToMapConverterTest.java
I've fixed bug. see [here](https://github.com/terasolunaorg/terasoluna-gfw/issues/297#issuecomment-121821531).
> #297: Modify to show empty string, if Iterable or array is empty

- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/el/ObjectToMapConverter.java
- terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/el/ObjectToMapConverterTest.java
> [5.0.x] #297: Modify to show empty string, if Iterable or array is empty

- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/el/ObjectToMapConverter.java
> #297: Polish some API docs

- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/el/ObjectToMapConverter.java
(cherry picked from commit 33bfbe618aa5e514afbf4b41422ba92580aa0dc2)
> [5.0.x] #297: Polish some API docs

- terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/el/ObjectToMapConverterTest.java
> #297: Restore assertions at the testConvert6_Array()

- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/el/ObjectToMapConverter.java
- terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/el/ObjectToMapConverterTest.java
For details see [here](https://github.com/terasolunaorg/terasoluna-gfw/issues/297#issuecomment-122253379) .
> #297: Support reset parameter, if element value is null

- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/el/ObjectToMapConverter.java
- terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/el/ObjectToMapConverterTest.java
(cherry picked from commit 7c788c50e099e5932b3134d534366af9ad6823c0)
> [5.0.x] #297: Support reset parameter, if element value is null

- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/el/Functions.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/el/ObjectToMapConverter.java
- terasoluna-gfw-web/src/main/resources/META-INF/functions.tld
I've improved API documents regarding `Map`, `Iterable` and Array property.
> #297: Improve API documents regarding conversion behavior of Map, Iterable and Array property

- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/el/Functions.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/el/ObjectToMapConverter.java
- terasoluna-gfw-web/src/main/resources/META-INF/functions.tld
> [5.0.x] #297: Improve API documents regarding conversion behavior of Map, Iterable and Array property

- README.md
> #352: Update version to 5.0.1.RELEASE in README.md

- README.md
> #353: Update version to 1.0.3.RELEASE in README.md

- README.md
(cherry picked from commit eed6a91c297396c5dd9c86b4f97371dd2ee7e450)
Please review #352 .
> [5.0.x] #352: Update version to 5.0.1.RELEASE in README.md

- terasoluna-gfw-common/pom.xml
- terasoluna-gfw-jpa/pom.xml
- terasoluna-gfw-mybatis2/pom.xml
- terasoluna-gfw-parent/pom.xml
- terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-security-core/pom.xml
- terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-web/pom.xml
> #356: Update to 1.0.4-SNAPSHOT

- terasoluna-gfw-common/pom.xml
- terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-jpa/pom.xml
- terasoluna-gfw-mybatis3/pom.xml
- terasoluna-gfw-parent/pom.xml
- terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-security-core/pom.xml
- terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-web/pom.xml
> #357: Update to 5.0.2-SNAPSHOT

- README.md
- terasoluna-gfw-parent/pom.xml
> #351: Remove the terasoluna-gfw-3rdparty repository setting from 5.x line

- README.md
- terasoluna-gfw-parent/pom.xml
(cherry picked from commit 6d70e7891b992b4a8d6ed2541f9546369308fd2b)
Please review #351 .
> [5.0.x] #351: Remove the terasoluna-gfw-3rdparty repository setting from 5.x line

- .travis.yml
Please review #368 .
**[Build Time]**
| Env | 1st(no cache) | 2nd(cached) | 3rd(cached) | 4th(cached) | 5th(cached) |
| ---- | :----: | :----: | :----: | :---: | :---: |
| Total | 10:38 | 08:57 | 08:41 | 08:27 | 07:44 |
| Oracle JDK8 | 03:07 | 03:37 | 02:57 | 03:16 | 02:33 |
| Oracle JDK7 | 02:51 | 01:43 | 01:58 | 01:51 | 01:49 |
| Open JDK7 | 02:27 | 01:56 | 01:43 | 01:46 | 01:45 |
| Open JDK6 | 02:03 | 01:41 | 02:03 | 01:34 | 01:37 |
> #368: travis-ci migrate to container-based infrastructure

- .travis.yml
(cherry picked from commit ab283978871b9c18e49ecfef764ad0582ca87791)
Please review #368 .
>  #368: travis-ci migrate to container-based infrastructure

- .travis.yml
- CONTRIBUTING.md
- mvn-build-all.sh
> #373: Add script file to execute maven build for all sub projects

- .travis.yml
- CONTRIBUTING.md
- mvn-build-all.sh
(cherry picked from commit b7ab05142b28ff2fbb1e1023d6018cbecc8e296d)
>  #373: Add script file to execute maven build for all sub projects

- CONTRIBUTING.md
- mvn-build-all.bat
I've added  bat file for windows machine.
> #373: Add bat file to execute maven build for all sub projects

- CONTRIBUTING.md
- mvn-build-all.bat
(cherry picked from commit 4dce81e0f3ff207fa451a8ec40d56b91b6462bc8)
> [1.0.x] #373: Add bat file to execute maven build for all sub projects

- CONTRIBUTING.md
- mvn-build-all.bat
(cherry picked from commit 4dce81e0f3ff207fa451a8ec40d56b91b6462bc8)
> [5.0.x] #373: Add bat file to execute maven build for all sub projects

- terasoluna-gfw-parent/pom.xml
> #279:Update to MyBatis 3.3.0

- .travis.yml
- terasoluna-gfw-jodatime/src/test/java/org/terasoluna/gfw/common/date/jodatime/JdbcAdjustedJodaTimeDateFactoryTest.java
- terasoluna-gfw-parent/pom.xml
- terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/util/ResponseUtilsTest.java
> Spring io platform version up. #362

- terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/codelist/JdbcCodeListTest.java
- terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/sequencer/JdbcSequencerTest.java
- terasoluna-gfw-jodatime/src/test/java/org/terasoluna/gfw/common/date/jodatime/JdbcFixedJodaTimeDateFactoryTest.java
I've changed to use `@Rollback` instead of `@TransactionConfiguration` (deprecating at Spring 4.2).
Please review #362 .
> Fix test due to SPR-13277 #362

- terasoluna-gfw-mybatis3/pom.xml
- terasoluna-gfw-parent/pom.xml
I've improved the dependency management of MyBatis3.
Please review #279 .
> Add the dependency management of MyBatis3 on parent pom file #279

- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraints/After.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraints/Before.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraints/ByteMax.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraints/ByteMin.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraints/Compare.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraints/package-info.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/AfterValidator.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/BeforeValidator.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/ByteMaxValidator.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/ByteMinValidator.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/CompareValidator.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/ConstraintValidatorsUtils.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/InternalValidator.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/InternalValidatorForCalendar.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/InternalValidatorForChronoLocalDate.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/InternalValidatorForChronoLocalDateTime.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/InternalValidatorForChronoZonedDateTime.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/InternalValidatorForDate.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/InternalValidatorForLocalTime.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/InternalValidatorForOffsetDateTime.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/InternalValidatorForOffsetTime.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/InternalValidatorForReadableInstant.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/InternalValidatorForReadablePartial.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/InternalValidatorForYear.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/InternalValidatorForYearMonth.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/package-info.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/package-info.java
I've polished some source codes.
* Add `package-info.java`
* Add `@since` 
* Remove unnecessary access modifier (remove `public` modifier)
* Change a range of applying `@SuppressWarnings`.
* Fix typo in JavaDoc and inline code comment
> Polishing #372

- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraints/ByteMax.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraints/ByteMin.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/ByteMaxValidator.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/ByteMinValidator.java
- terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/ByteMaxTest.java
- terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/ByteMinTest.java
I've fixed https://github.com/terasolunaorg/terasoluna-gfw/issues/372#issuecomment-157086197.
> Support CharSequence on Validator for @ByteMin and @ByteMax #372

- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraints/After.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraints/Before.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraints/ByteMax.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraints/ByteMin.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraints/Compare.java
I've fixed https://github.com/terasolunaorg/terasoluna-gfw/issues/372#issuecomment-157261487.
> Remove @ReportAsSingleViolation from new constraint annotations #372

- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/ExistInCodeList.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenCheck.java
> Add @Documented on annotations #399

- terasoluna-gfw-parent/pom.xml
please review #362[spring io pf version 2.0.0. RELEASE]
> change springIoPf version #362

- terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/AfterForJSR310Test.java
- terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/AfterForJodaTimeTest.java
- terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/AfterTest.java
- terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/BeforeForJSR310Test.java
- terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/BeforeForJodaTimeTest.java
- terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/BeforeTest.java
- terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/ByteMaxTest.java
- terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/ByteMinTest.java
- terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/CompareTest.java
I removed dependence on Lombok, because, it causes a problem in case of using eclipse.
Please review #372.
> Remove lombok, and add getter,setter codes #372

- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraints/Compare.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/CompareValidator.java
- terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/CompareTest.java
I've refactor enum.
* Change enum name (`Path` -> `Node` )
* Change constants name of `LEFT` and `RIGHT` ( append `_PROPERTY`)
**Note:**
I will submit other refactoring at later.
> Refactor enum for specifying a node which bind message #372

- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/logging/HttpSessionEventLoggingListener.java
I've polished coding style.
Please review #136 .
> Modify to call logging method using variable length arguments #136

- mvn-build-all.bat
- mvn-build-all.sh
I've added `terasoluna-gfw-validator` as build target.
> Add terasoluna-gfw-validator on mvn-build-all.sh #372

- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/ExistInCodeList.java
- terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/codelist/ExistInCodeListTest.java
- terasoluna-gfw-common/src/test/resources/org/terasoluna/gfw/common/codelist/ExistInCodeListTest-context.xml
> Add CONSTRUCTOR and PARAMETER on @ExistInCodeList #401

- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraints/Compare.java
- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/CompareValidator.java
- terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/CompareTest.java
For response of this issue comment, I sent this pull request.
https://github.com/terasolunaorg/terasoluna-gfw/issues/372#issuecomment-156920292 About  `null`  value
https://github.com/terasolunaorg/terasoluna-gfw/issues/372#issuecomment-160121086
Please review #372.
> Improve the handling nullValue of @Compare #372

- .travis.yml
- terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common/pom.xml
- terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-parent/pom.xml
- terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-web/pom.xml
Please review #380 .
Coverages refer to https://coveralls.io/github/terasolunaorg/terasoluna-gfw.
> Support coveralls #380

- terasoluna-gfw-parent/pom.xml
> Add codepoints artifacts into dependencyManagement #390

- README.md
> Add badge of caveralls #380

- .travis.yml
- README.md
- terasoluna-gfw-common/pom.xml
- terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-parent/pom.xml
- terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-web/pom.xml
I've backported to 5.0.x by manually.
Please review #380 .
> [5.0.x] Support coveralls #380

- .travis.yml
- README.md
- terasoluna-gfw-common/pom.xml
- terasoluna-gfw-parent/pom.xml
- terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-web/pom.xml
I've backported to 1.0.x by manually.
Please review #380 .
> [1.0.x] Support coveralls #380

- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/ExistInCodeList.java
Please review #401.
For details, please refer https://github.com/terasolunaorg/terasoluna-gfw/issues/401#issuecomment-161158232.
> Remove CONSTRUCTOR from @Target of @ExistInCodeList #401

- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraints/Compare.java
- terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/ByteMaxTest.java
- terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/ByteMinTest.java
- terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/CompareTest.java
- terasoluna-gfw-validator/src/test/resources/ValidationMessages.properties
> Correct typo, and improve validation message #430

- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/ExistInCodeList.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/validator/ExistInCodeListValidatorForCharSequence.java
- terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/codelist/ExistInCodeListTest.java
Replace generic type( String  ->  CharSequence ) and change class name and add test case.
Please review #402 .
> Suppot CharSequence #402

- mvn-build-all.bat
- mvn-build-all.sh
- terasoluna-gfw-parent/pom.xml
- terasoluna-gfw-string/pom.xml
> Add terasoluna-gfw-string's dependencyManagement. #367

- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenCheck.java
- terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenInfoStoreTest.java
- terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenSampleNamespaceController.java
Support @AliasFor and add testcase in @TransactionTokenCheck.
Please review #364 .
> Support @AliasFor in @TransactionTokenCheck #364

- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/validator/ExistInCodeListValidatorForCharSequence.java
> Fix Javadoc of ExistInCodeListValidatorForCharSequence #402

- README.md
(cherry picked from commit ace0e9a99a6f3e2bcdc2eeb1cccd268dd13f3b26)
Please review #440 .
> Fix end tag of <dependency> #440

- terasoluna-gfw-parent/pom.xml
* Apply fix version for COLLECTIONS-580
Please review #444 .
**Note:**
CI of functional tests and Sample application has been succeeded using Commons-Collections 3.2.2.
* https://travis-ci.org/terasolunaorg/terasoluna-gfw-functionaltest/builds/97601142
* https://travis-ci.org/terasolunaorg/terasoluna-tourreservation/builds/97601351
> [1.0.x] Update to Commons-Collections 3.3.2 #444

- terasoluna-gfw-parent/pom.xml
> Update to Spring IO Platform 2.0.1 #362

- terasoluna-gfw-parent/pom.xml
(cherry picked from commit b5201f8c79e8bba0f3e2d56051be25508c9c7dfa)
Please review #451 .
> [5.0.x] Add pluginManagement of cargo-maven2-plugin #451

- terasoluna-gfw-parent/pom.xml
I've backported to 1.0.x by manually.
Please review #451 .
> [1.0.x] Add pluginManagement of cargo-maven2-plugin #451

- mvn-build-all-targets.txt
- mvn-build-all.bat
- mvn-build-all.sh
I've improve script file to build artifacts. (modify as manage build targets using list file)
Please review #373.
> Add list file to manage build target #373

- mvn-build-all-targets.txt
- mvn-build-all.bat
- mvn-build-all.sh
I've backported to 5.0.x by manually.
> [5.0.x] Add list file to manage build target #373

- mvn-build-all-targets.txt
- mvn-build-all.bat
- mvn-build-all.sh
I've backported to 1.0.x by manually.
> [1.0.x] Add list file to manage build target #373

- terasoluna-gfw-parent/pom.xml
> Update tomcat7 version #318

- terasoluna-gfw-mybatis3/pom.xml
- terasoluna-gfw-parent/pom.xml
Please review #464.
backport for #383 , #393.
> Update MyBatis3 and Add DependencyManagement #464

- terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/ByteMaxTest.java
- terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/ByteMinTest.java
- terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/CompareTest.java
- terasoluna-gfw-validator/src/test/resources/ValidationMessages.properties
> improve validation message of terasoluna-gfw-validator #468

- terasoluna-gfw-security-web/src/main/java/org/terasoluna/gfw/security/web/redirect/RedirectAuthenticationHandler.java
- terasoluna-gfw-security-web/src/test/java/org/terasoluna/gfw/security/web/redirect/RedirectAuthenticationHandlerTest.java
Please review #462  .
RedirectAuthenticationHandler.java
Add @deprecated comment
Add @Deprecated annotation
RedirectAuthenticationHandlerTest.java
Add @SuppressWarnings annotation
> #462: Add @Depricated on RedirectAuthenticationHandler

- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/ReadWriteLockMapWrapper.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/exception/DefaultExceptionLevelResolver.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/exception/ExceptionLogger.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/exception/SimpleMappingExceptionCodeResolver.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/exception/SystemException.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/message/ResultMessage.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/message/ResultMessageUtils.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/message/ResultMessages.java
- terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/message/ResultMessageTest.java
- terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/message/ResultMessagesTest.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/codelist/CodeListInterceptor.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/download/AbstractFileDownloadView.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/el/Functions.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/el/ObjectToMapConverter.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/logging/TraceLoggingInterceptor.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/message/MessagesPanelTag.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/mvc/support/CompositeRequestDataValueProcessor.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/mvc/support/ProcessActionInvocationHelper.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/mvc/support/RequestDataValueProcessorAdaptor.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/pagination/PaginationTag.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/HttpSessionTransactionTokenStore.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionToken.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenInfoStore.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/util/HtmlEscapeUtils.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/util/JspTagUtils.java
- terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/pagination/PaginationTagTest.java
please review #428 .
backport of #461 for 5.0.x
> [5.0.x] fix SonarQube alerts #428

- terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
I've polished `pom.xml` of `terasoluna-gfw-codepoints` .
Please review #390 .
> Remove unnecessary version tag on pom.xml #390

- terasoluna-gfw-validator/pom.xml
I've polished `pom.xml` of `terasoluna-gfw-validator` .
> Remove joda-time #372

- CONTRIBUTING.md
> Fix a rule for git commit comments #386

- CONTRIBUTING.md
> [5.0.x] Modify a sentence #386

- CONTRIBUTING.md
> [1.0.x] Modify a sentence #386

- CONTRIBUTING.md
> Modify a sentence #386

- README.md
> Update version to 5.1.0.RELEASE in README.md #502

- README.md
> [5.1.x]Update version to 5.1.0.RELEASE in README.md #502

- README.md
> Update version to 5.0.2.RELEASE in README.md #501

- README.md
> Update version to 1.0.4.RELEASE in README.md #500

- terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common/pom.xml
- terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-jpa/pom.xml
- terasoluna-gfw-mybatis3/pom.xml
- terasoluna-gfw-parent/pom.xml
- terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-security-core/pom.xml
- terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-string/pom.xml
- terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-web/pom.xml
> Update to 5.2.0-SNAPSHOT #494

- terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common/pom.xml
- terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-jpa/pom.xml
- terasoluna-gfw-mybatis3/pom.xml
- terasoluna-gfw-parent/pom.xml
- terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-security-core/pom.xml
- terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-string/pom.xml
- terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-web/pom.xml
> Update to 5.1.1-SNAPSHOT #497

- terasoluna-gfw-common/pom.xml
- terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-jpa/pom.xml
- terasoluna-gfw-mybatis3/pom.xml
- terasoluna-gfw-parent/pom.xml
- terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-security-core/pom.xml
- terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-web/pom.xml
> Update to 5.0.3-SNAPSHOT #493

- terasoluna-gfw-common/pom.xml
- terasoluna-gfw-jpa/pom.xml
- terasoluna-gfw-mybatis2/pom.xml
- terasoluna-gfw-parent/pom.xml
- terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-security-core/pom.xml
- terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-web/pom.xml
> Update to 1.0.5-SNAPSHOT #492

- terasoluna-gfw-parent/pom.xml
I've updated selenium web driver version.
Please review #511 .
> Note : Travis-CI is successful.
>
> * https://travis-ci.org/terasolunaorg/terasoluna-gfw-functionaltest
> * https://travis-ci.org/terasolunaorg/terasoluna-tourreservation
> Update selenium 2.52.0 #511

- ISSUE_TEMPLATE.md
- PULL_REQUEST_TEMPLATE.md
> Add issue and PR template #509

- terasoluna-gfw-parent/pom.xml
Please review #463 .
I've added test case classes of spring security.
> Add pattern of testcase class #463

- terasoluna-gfw-web-jsp/pom.xml
> taglibs-standard-jstlel change scope to provided and add optional #524

- CONTRIBUTING.md
> Modify url for creating a new issue in CONTRIBUTING.md #509

- README.md
> Update README.md #514

- README.md
> Add the badge of Apache License #542

- README.md
Please review #542.
Note: I've modified other URLs.
> [5.1.x] Add the badge of Apache License #542

- README.md
Please review #542.
Note: I've modified other ULRs.
> [5.0.x] Add the badge of Apache License #542

- README.md
> [1.0.x] Add the badge of Apache License #542

- README.md
Please review #514 .
(cherry picked from commit 9b5ef101f8e5810a8797b5732f18e0cc083c7c6a)
> Update README.md #514(backport 1.0.x)

- README.md
> Change png -> svg for Travis CI badge #547

- README.md
> [5.1.x] Change png -> svg for Travis CI badge #547

- README.md
> [5.0.x] Change png -> svg for Travis CI badge #547

- terasoluna-gfw-jpa/pom.xml
- terasoluna-gfw-mybatis3/pom.xml
- terasoluna-gfw-parent/pom.xml
- terasoluna-gfw-security-core/pom.xml
- terasoluna-gfw-security-web/pom.xml
Please review #519 .
Set 'pom' to Packaging type of artifacts and add 'type' to dependency due #519
> Set 'pom' to Packaging type of artifacts and add 'type' to dependency due #519

- terasoluna-gfw-web-jsp/src/main/java/org/terasoluna/gfw/web/message/MessagesPanelTag.java
- terasoluna-gfw-web-jsp/src/main/java/org/terasoluna/gfw/web/pagination/PaginationTag.java
- terasoluna-gfw-web-jsp/src/test/java/org/terasoluna/gfw/web/message/MessagesPanelTagTest.java
- terasoluna-gfw-web-jsp/src/test/java/org/terasoluna/gfw/web/pagination/PaginationTagTest.java
> MessagePanelTag doesn't close with </div> when it's empty #554 

- terasoluna-gfw-web-jsp/src/main/java/org/terasoluna/gfw/web/message/MessagesPanelTag.java
- terasoluna-gfw-web-jsp/src/main/java/org/terasoluna/gfw/web/pagination/PaginationTag.java
- terasoluna-gfw-web-jsp/src/test/java/org/terasoluna/gfw/web/message/MessagesPanelTagTest.java
- terasoluna-gfw-web-jsp/src/test/java/org/terasoluna/gfw/web/pagination/PaginationTagTest.java
> [5.1.x] MessagePanelTag doesn't close with </div> when it's empty #554

- terasoluna-gfw-parent/pom.xml
> add distributionManagement for deploying terasoluna-gfw-parent alone #508

- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
Please review #562 
The original PR was #573. Modified for All comments from the PR.
> Support jsr310 #562

- terasoluna-gfw-parent/pom.xml
> [5.1.x] OSS version update  #569

- terasoluna-gfw-parent/pom.xml
> OSS version update #569

- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/HttpSessionTransactionTokenStore.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenContextImpl.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenInfo.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenInterceptor.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenStore.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenType.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/token/transaction/HttpSessionTransactionTokenStoreTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenContextImplTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenInfoTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenInterceptorTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenSampleController.java
Please review #565 
@ikeyat 
レビューお願いします。
JavaDocは後ずけで良いとのことでしたので省略しています。
また、以下の仕様にて実装しています。
BEGIN ：検証をまったく行わず、新たにトークンを発行する
IN    ：トークンの妥当性を検証（NameSpace,TokenKey,TokenValueの一致）し、
　　　　検証ＯＫの場合トークンを更新する
END   ：トークンの妥当性を検証（NameSpace,TokenKey,TokenValueの一致）し、
　　　　検証ＯＫの場合トークンを削除する
CHECK ：トークンの妥当性を検証（NameSpace,TokenKey,TokenValueの一致）し、
　　　　検証ＯＫの場合トークンを維持する
UPDATE：トークンの妥当性を検証（NameSpace,TokenKey,TokenValueの一致）はしないが
　　　　更新対象トークンの存在チェックとして
　　　　リクエストパラメータのトークンにNameSpace,TokenKey,TokenValueが存在すること
　　　　セッションに当該キー（NameSpace,TokenKey）が存在することの検証は行う。
　　　　存在チェックがOKであれば当該のトークンのTokenValueを更新する。
　　　　NGの場合はIllegalStateExceptionをthrowする
KEEP  ：トークンの妥当性を検証（TokenValueの一致）はしないが
　　　　引継対象トークンのチェックとして
　　　　リクエストパラメータのトークンにNameSpace,TokenKey,TokenValueが存在することの検証は行う。
　　　　チェックがOKであれば入力のトークンをそのまま次のトークンとして再設定する …
> add trasaction token type check, update and keep. #565

- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/HttpSessionTransactionTokenStore.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenContextImpl.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenInfo.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenInterceptor.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenStore.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenType.java
- terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/token/transaction/HttpSessionTransactionTokenStoreTest.java
- terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenContextImplTest.java
- terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenInfoTest.java
- terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenInterceptorTest.java
- terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenSampleController.java
Please review #565.
(cherry picked from commit d7866baeaacb019553f8539301e277c4a70fa2cc)
> [5.1.x] add trasaction token type check, update and keep. #565

- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> add new comments to categorize properties #508

- terasoluna-gfw-parent/pom.xml
> update spring-io-platform to 2.0.6 #569

- terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
> remove duplicate dependencies #508

- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/src/main/java/org/terasoluna/gfw/common/codepoints/catalog/JIS_X_0208_SpecialChars.java
> #560_Add_class_javadoc_JISX_0208_Codepoints

- terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/src/main/java/org/terasoluna/gfw/common/codepoints/catalog/JIS_X_0208_SpecialChars.java
Please review #560 .
(cherry picked from commit e0c71869871a9b22f1ef58a689a86083457c1abb)
> #560_Add_class_javadoc_JISX_0208_Codepoints_backport

- terasoluna-gfw-parent/pom.xml
> update tomcat version on cargo #577

- terasoluna-gfw-parent/pom.xml
> Update OSS Version (Spring 3.2.16 -> 3.2.17) #584

- README.md
Please review #568.
(cherry picked from commit 17d8a26923f955da7564e98cde23e17e948f875d)
> [5.1.x] Update README.md

- README.md
Please review #568.
(cherry picked from commit 17d8a26923f955da7564e98cde23e17e948f875d)
> [5.0.x] Update README.md

- README.md
Please review #568.
(cherry picked from commit 17d8a26923f955da7564e98cde23e17e948f875d)
Conflicts:
README.md
> [1.0.x] Update README.md

- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/codelist/CodeListInterceptor.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/el/Functions.java
> [5.1.x]remove sonar qube warning#582

- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenInterceptor.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenInterceptorTest.java
> Fix TransactionTokenInterceptor throws NPE when an Exception is thrown in preHandle. #564

- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/HttpSessionTransactionTokenStore.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenInfo.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenInterceptor.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenStore.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenType.java
> write javadoc. #565

- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenContext.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenContextImpl.java
> TransactionTokenContext deprecated. #593

- .travis.yml
- mvn-build-all.bat
- mvn-build-all.sh
- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> modify gfw project structure #567

- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/HttpSessionTransactionTokenStore.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenInfo.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenInterceptor.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenStore.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenType.java
Please review #565.
Cherry-picked from #591.
> [5.1.x] write javadoc. #565

- .travis.yml
- pom.xml
- terasoluna-gfw-parent/pom.xml
> enable to deploy to Maven Central repository #425

- README.md
> update to 5.2.0.RELEASE in README.md #613

- README.md
> [5.2.x] update to 5.2.0.RELEASE in README.md #613

- README.md
> update to 5.1.1.RELEASE in README.md #613

- README.md
> update to 1.0.5.RELEASE in README.md #613

- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-core-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> Update SNAPSHOT version to 5.3.0-SNAPSHOT  #612

- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-core-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> Update SNAPSHOT version to 5.2.1-SNAPSHOT #612

- terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common/pom.xml
- terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-jpa/pom.xml
- terasoluna-gfw-mybatis3/pom.xml
- terasoluna-gfw-parent/pom.xml
- terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-security-core/pom.xml
- terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-string/pom.xml
- terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-web/pom.xml
> Update SNAPSHOT version to 5.1.2-SNAPSHOT #612

- terasoluna-gfw-common/pom.xml
- terasoluna-gfw-jpa/pom.xml
- terasoluna-gfw-mybatis2/pom.xml
- terasoluna-gfw-parent/pom.xml
- terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-security-core/pom.xml
- terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-web/pom.xml
> Update SNAPSHOT version to 1.0.6-SNAPSHOT #612

- README.md
> change travis & coverage branch in README.md #613

- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/CompareValidator.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/CompareTest.java
> Modify error message output node in @Compare requireBoth check.#634

- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/CompareValidator.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/CompareTest.java
Please review #634 .
(cherry picked from commit ccfdf8ba6f41267d0c7d43070a2159eab2a7a34c)
> [5.2.x]Modify error message output node in @Compare requireBoth check.#634

- terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/CompareValidator.java
- terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/CompareTest.java
Please review #634 .
(cherry picked from commit ccfdf8ba6f41267d0c7d43070a2159eab2a7a34c)
> [5.1.x]Modify error message output node in @Compare requireBoth check.#634

- terasoluna-gfw-parent/pom.xml
> update oss version for 5.3.0 #640 

- terasoluna-gfw-parent/pom.xml
> update oss version for 5.3.0 #643

- terasoluna-gfw-parent/pom.xml
> Update to cargo-maven2-plugin 1.6.2 #646

- terasoluna-gfw-parent/pom.xml
> Change the property key for specifying a URIEncoding #646

- terasoluna-gfw-parent/pom.xml
> Update to Tomcat 8.0.39 for cargo #652

- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/message/ResultMessage.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/message/ResultMessages.java
- terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/message/ResultMessageTest.java
- terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/message/ResultMessagesTest.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/codelist/CodeListInterceptor.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/pagination/PaginationTag.java
- terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/pagination/PaginationTagTest.java
Please review #663 .
Referred to #428 and #461 for way to fix the warnings.
> [1.0.x] Remove SonarQube Warning  #663 

- README.md
- pom.xml
- terasoluna-gfw-parent/pom.xml
> Modified /pom.xml and /terasoluna-gfw-parent/pom.xml for Maven Central.#664

- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/message/ResultMessage.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/message/ResultMessages.java
- terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/message/ResultMessageTest.java
- terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/message/ResultMessagesTest.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/codelist/CodeListInterceptor.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/pagination/PaginationTag.java
- terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/pagination/PaginationTagTest.java
> [1.0.x]code formatted.#674

- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/message/ResultMessage.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/message/ResultMessages.java
- terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/query/LikeConditionEscape.java
- terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/message/ResultMessageTest.java
- terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/message/ResultMessagesTest.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/codelist/CodeListInterceptor.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/pagination/PaginationTag.java
- terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/HttpSessionTransactionTokenStore.java
- terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/pagination/PaginationTagTest.java
> [5.0.x]code formatted.#674

- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-core-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> [master]Update SNAPSHOT version to 5.4.0-SNAPSHOT #685

- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-core-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> [5.3.x]Update SNAPSHOT version to 5.3.1-SNAPSHOT #685

- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-core-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> [5.2.x]Update SNAPSHOT version to 5.2.2-SNAPSHOT #685

- terasoluna-gfw-common/pom.xml
- terasoluna-gfw-jpa/pom.xml
- terasoluna-gfw-mybatis2/pom.xml
- terasoluna-gfw-parent/pom.xml
- terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-security-core/pom.xml
- terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-web/pom.xml
> [1.0.x]Update SNAPSHOT version to 1.0.7-SNAPSHOT #685

- README.md
> [master]Update version to 5.3.0.RELEASE in README.md.#684

- README.md
> [5.3.x]Update version to 5.3.0.RELEASE and Change link to badge in README.md .#684

- README.md
> [5.2.x]Update version to 5.2.1.RELEASE in README.md.#684

- README.md
> [1.0.x]Update version to 1.0.6.RELEASE in README.md.#684

- README.md
> [5.2.x]Modify "Projects of Common Library" link in README.md.#694

- README.md
> [5.3.x]Modify "Projects of Common Library" link in README.md.#694

- README.md
> [5.1.x]Modify "Projects of Common Library" link in README.md.#694

- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/resources/org/terasoluna/gfw/common/codelist/ExistInCodeListTest-context.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/resources/org/terasoluna/gfw/common/codelist/i18n/simpleI18nCodeList.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/resources/org/terasoluna/gfw/common/exception/ResultMessagesLoggingInterceptorTest.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/resources/test-context.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/src/test/resources/test-context.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/src/test/resources/logback.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/resources/logback.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/resources/org/terasoluna/gfw/web/codelist/CodeListInterceptorTest.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/resources/test-context.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
Please review #680 #700 .
I re-set the standard of xml format to 100 chars per line .
> Modified code format(xml) for line width 100 #680

- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/resources/org/terasoluna/gfw/common/codelist/ExistInCodeListTest-context.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/resources/org/terasoluna/gfw/common/codelist/i18n/simpleI18nCodeList.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/resources/org/terasoluna/gfw/common/exception/ResultMessagesLoggingInterceptorTest.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/resources/test-context.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/src/test/resources/test-context.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/src/test/resources/logback.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/resources/logback.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/resources/org/terasoluna/gfw/web/codelist/CodeListInterceptorTest.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/resources/test-context.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
Please review #680 #704 .
I re-set the standard of xml format to 100 chars per line .
> [5.3.x] Modified code format(xml) for line width 100 #680

- pom.xml
- terasoluna-gfw-parent/pom.xml
> Upgrade to nexus-staging-maven-plugin 1.6.8 #683

- pom.xml
- terasoluna-gfw-parent/pom.xml
(cherry picked from commit d87ea48a4722fa12b008fc8b9aef1f687c66d0de)
Please review #683.
> [5.3.x] Upgrade to nexus-staging-maven-plugin 1.6.8 #683

- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/exception/ExceptionLoggingFilter.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/exception/ExceptionLoggingFilterTest.java
> Changed the log level of ExceptionLoggingFilter to ERROR. #702

- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraints/Compare.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/CompareTest.java
> Add NOT_EQUAL operator on @Compare #711

- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraints/Compare.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/CompareTest.java
(cherry picked from commit b9633a5b951bf74e80f3f5e8212ccc6e625ca70a)
Please review #711 .
> [5.3.x] Add NOT_EQUAL operator on @Compare #711

- .travis.yml
> Drop oraclejdk7 from ".travis.yml" #666

- .travis.yml
(cherry picked from commit 2bf60c0d4361ae936fdaf8adc18ee1cab36f194d)
Please review #666.
> [5.3.x]Drop oraclejdk7 from .travis.yml #666

- ISSUE_TEMPLATE.md
> Update issue template #718

- .travis.yml
> [1.0.x]Drop oraclejdk7 and openjdk6 from ".travis.yml". #666 and #725

- ISSUE_TEMPLATE.md
> Add Fanal Solution section to Issue Template. #730

- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/exception/ResultMessagesNotificationException.java
Misprints modified, Please review #701
> Modify misprints in Javadoc #701

- README.md
> Add description for terasoluna-gfw-codepoints to README.md #734

- terasoluna-gfw-parent/pom.xml
> Upgrade to MyBatis 3.4.5 #732

- README.md
> [5.3.x] Add description for terasoluna-gfw-codepoints to README.md #734

- README.md
> [5.2.x] Add description for terasoluna-gfw-codepoints to README.md #734

- terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> Drop the mybatis-typehandlers-jsr310 #715

- README.md
> [5.1.x] Add description for terasoluna-gfw-codepoints to README.md #734

- .travis.yml
> Support openjdk8 on Travis CI #739

- .travis.yml
> [5.3.x] Support openjdk8 on Travis CI #739

- .travis.yml
> [5.2.x] Support openjdk8 on Travis CI #739

- .travis.yml
> [5.1.x] Support openjdk8 on Travis CI #739

- .travis.yml
> [5.0.x] Support openjdk8 on Travis CI #739

- .travis.yml
> [1.0.x] Support openjdk8 on Travis CI #739

- terasoluna-gfw-parent/pom.xml
> upgrade spring io platform version to Brussels-SR5 #772 #741

- README.md
> fix terasoluna-gfw version in README.md #776

- README.md
> [5.3.x] fix terasoluna-gfw version in README.md #776

- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-core-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> [5.3.x] fix SNAPSHOT version in pom.xml #778

- ISSUE_TEMPLATE.md
> fix Version/s' in 5.3.x next release changed to 5.3.2. #780

- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraints/Compare.java
> fix release version written in javadoc. #783

- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraints/Compare.java
(cherry picked from commit 5e531027097918bb275caa9c76547c0a356a0b85)
Please review #783.
> [5.3.x] fix release version written in javadoc. #783

- README.md
> update version to 5.4.0.RELEASE in README.md #787

- README.md
> [5.4.x] update version to 5.4.0.RELEASE and change link to badge in README.md #787

- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-core-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> [5.4.x] update to 5.4.1-SNAPSHOT #788

- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-core-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> update to 5.5.0-SNAPSHOT #788

- ISSUE_TEMPLATE.md
> update 'Fix Version/s' #793

- terasoluna-gfw-parent/pom.xml
> [5.4.x] update spring and spring security version #797

- terasoluna-gfw-parent/pom.xml
> [5.3.x] update spring and spring security version #797

- terasoluna-gfw-parent/pom.xml
> Describe spring and spring security before IO platform #797

- terasoluna-gfw-parent/pom.xml
> [5.3.x] Describe spring and spring security before IO platform #797

- ISSUE_TEMPLATE.md
- README.md
> update issue template and readme to 5.4.1 release #804

- README.md
- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-core-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> [5.4.x] update version of both readme and pom.xml #804

- README.md
- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-core-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> [5.3.x] update version of both readme and pom.xml #804

- terasoluna-gfw-parent/pom.xml
Please review #810
terasoluna-gfw / terasoluna-gfw-parent / pom.xml in Line 395
Change io.spring.platform.version from "Brussels-SR 5" to "Cairo-SR 1".
> upgrade to spring io platform Cairo-SR1. #810

- terasoluna-gfw-parent/pom.xml
Reverts terasolunaorg/terasoluna-gfw#814
> Revert "upgrade to tomcat v9.0.6 #810"

- terasoluna-gfw-parent/pom.xml
Reverts terasolunaorg/terasoluna-gfw#811
> Revert "upgrade to spring io platform Cairo-SR1. #810"

- terasoluna-gfw-parent/pom.xml
Please review #813
terasoluna-gfw / terasoluna-gfw-parent / pom.xml
Change MyBatis version to v3.4.6 and change MyBatis.spring version to v1.3.2
> [5.5.0.RC2]Upgrade to MyBatis #813

- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
Please review #823 
Change dozer  version to v6.2.0
> [5.5.0.RC2] Upgrade to dozer v6.2.0 #823

- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-core-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> update to 5.5.0.RC2-SNAPSHOT #825

- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
Please review #829
Change dozer version to v6.4.0
> Upgrade to dozer v6.4.0 #829

- terasoluna-gfw-parent/pom.xml
> Upgrade to Spring IO platform Cairio-SR3 #830

- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/el/Functions.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/el/FunctionsTest.java
> Encode '+' due to Spring Framework 5.x specification change.

- terasoluna-gfw-parent/pom.xml
> fix override tomcat library version #842

- terasoluna-gfw-parent/pom.xml
> update cargo using tomcat version #843

- terasoluna-gfw-parent/pom.xml
> add tomcat dependency version #847

- terasoluna-gfw-parent/pom.xml
> Upgrade to Spring IO platform Brussels-SR14 #849

- README.md
Please review #728 .
deleted the explanation as described in Issue.
> delete repository setting of terasoluna-gfw-releases #728

- README.md
Please review #728.
backport.
(cherry-pick : 1654c74)
> [5.3.x] delete repository setting of terasoluna-gfw-releases #728

- README.md
(cherry picked from commit 1654c74f836656e972749e680ea5d1cf80de505b)
Please review #728
> [5.4.x] delete descript deploy terasoluna-gfw #728

- terasoluna-gfw-parent/pom.xml
> Upgrade to Spring IO platform Brussels-SR15 #849

- .travis.yml
- ISSUE_TEMPLATE.md
- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/src/main/java/org/terasoluna/gfw/common/codepoints/catalog/JIS_X_0208_SpecialChars.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-core-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> apply spring boot dependencies 2.1.2, mybatis 3.5.0 #858 #859 #860

- .travis.yml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/src/main/java/org/terasoluna/gfw/common/codepoints/CodePoints.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/message/ResultMessage.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/message/ResultMessages.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/query/LikeConditionEscape.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/src/main/java/org/terasoluna/gfw/web/message/MessagesPanelTag.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/src/main/java/org/terasoluna/gfw/web/pagination/PaginationTag.java
> fix javadoc errors for jdk11 #864

- terasoluna-gfw-parent/pom.xml
> update google guava 27.0.1-jre #862

- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/src/main/java/org/terasoluna/gfw/common/codepoints/CodePoints.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/message/ResultMessage.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/message/ResultMessages.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/query/LikeConditionEscape.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/src/main/java/org/terasoluna/gfw/web/message/MessagesPanelTag.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/src/main/java/org/terasoluna/gfw/web/pagination/PaginationTag.java
Please review #864.
I fixed all warnings of javadoc on jdk 8.
> [5.4.x] fix javadoc warnings #864

- terasoluna-gfw-parent/pom.xml
> Update spring-security-oauth2 to 2.2.4.RELEASE #868

- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/i18n/AbstractI18nCodeList.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/i18n/I18nCodeList.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/i18n/SimpleI18nCodeList.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/codelist/i18n/AbstractI18nCodeListTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/codelist/i18n/SimpleI18nCodeListTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/resources/org/terasoluna/gfw/common/codelist/i18n/simpleI18nCodeList.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/codelist/CodeListInterceptor.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/codelist/CodeListInterceptorTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/resources/org/terasoluna/gfw/web/codelist/CodeListInterceptorTest.xml
Please review #363, #803.
_I do not maintained JUnit test code because those test code never maintained correctly before ever. I modified existing method but the test for that method is not exist. I talked to @hirakuriy about this issue and he said you do not need to maintain JUnit test code._
> Improve i18nCodeList locale resolution. #363 #803

- terasoluna-gfw-parent/pom.xml
> [5.4.x] update spring io and oauth2 #870

- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
(cherry picked from commit 56805e0cc19fc967af6293b36d5b696cbda335f6)
Please review #736 .
> [5.4.x]move dependency jacson-datatype-joda to gfw-jodatime-dependencies #736 (#837)

- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/i18n/SimpleI18nCodeList.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/codelist/i18n/SimpleI18nCodeListTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/resources/org/terasoluna/gfw/common/codelist/i18n/simpleI18nCodeList.xml
> add default locale resolve function #363

- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraints/ByteMin.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraints/ByteSize.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraints/Compare.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/ByteMinValidator.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/ByteSizeValidator.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/AbstractConstraintsTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/ByteMaxTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/ByteMinTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/ByteSizeTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/test/resources/ValidationMessages.properties
@kazuki43zoo 
I tried #761! Please review, if it's OK with you.
Notice:: Sorry, please let project members to decide to merge or not.
> create @ByteSize validator #761

- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/ByteSizeValidator.java
> fix typo #761

- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/ExistInCodeList.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/NumberRangeCodeList.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/validator/AbstractExistInCodeListValidator.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/validator/ExistInCodeListValidatorForNumber.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/codelist/ExistInCodeListTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/resources/org/terasoluna/gfw/common/codelist/ExistInCodeListTest-context.xml
> @ExistInCodeList enable to validate Number #877

- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
> remove deprecated hibernate-entitymanager #875

- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/i18n/AbstractI18nCodeList.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/i18n/ReloadableI18nCodeList.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/i18n/SimpleI18nCodeList.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/i18n/SimpleReloadableI18nCodeList.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/codelist/i18n/AbstractI18nCodeListTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/codelist/i18n/SimpleReloadableI18nCodeListTest.java
> new feature reloadable i18n codelist #11

- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/i18n/ReloadableI18nCodeList.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/i18n/SimpleReloadableI18nCodeList.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/codelist/CodeListInterceptor.java
> change @since version to 5.4.2 #809 #11

- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/ByteMaxTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/ByteMinTest.java
> adjust testcase signature #761

- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/ExistInCodeList.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/NumberRangeCodeList.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/validator/AbstractExistInCodeListValidator.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/validator/ExistInCodeListValidatorForNumber.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/codelist/ExistInCodeListTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/resources/org/terasoluna/gfw/common/codelist/ExistInCodeListTest-context.xml
(cherry picked from commit d21edc30a8c75fed462f35d2dcad8f7b10a016c9)
Please review #877.
> [5.4.x] @ExistInCodeList enable to validate Number #877

- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
> remove dependency of jcl-over-slf4j #889

- ISSUE_TEMPLATE.md
- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-core-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> update to 5.6.0-snapshot #891

- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/ByteMaxTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/ByteMinTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-core-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> udpate to 5.5.2-snapshot #891

- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/i18n/AbstractI18nCodeList.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/i18n/ReloadableI18nCodeList.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/i18n/SimpleI18nCodeList.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/i18n/SimpleReloadableI18nCodeList.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/codelist/i18n/AbstractI18nCodeListTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/codelist/i18n/SimpleReloadableI18nCodeListTest.java
(cherry picked from commit 786e349d94bc052028f59c037a6fcff7eb83d335)
Please review #11 .
The creation policy is as follows. 
* based on #882, #883 (new feature reloadable i18n codelist) 
* excluded #840 (improve i18n codelist locale resolution)
> [5.4.x] new feature reloadable i18n codelist #11

- terasoluna-gfw-parent/pom.xml
> update to Brussels-SR17 #896

- terasoluna-gfw-parent/pom.xml
> remove spring-security-oauth2 dependency #898

- terasoluna-gfw-parent/pom.xml
Please review https://github.com/terasolunaorg/terasoluna-gfw/issues/896#issuecomment-480724747
> update tomcat8 > 8.5.39 #896

- terasoluna-gfw-parent/pom.xml
> [5.4.2.RELEASE] Downgrade Tomcat version -> 8.5.38 #902

- terasoluna-gfw-parent/pom.xml
> [5.4.x] apply mybatis 3.4.6 and mybatis-Spring 1.3.2 #904

- terasoluna-gfw-parent/pom.xml
> [5.4.2.RELEASE]update tomcat version 8.5.40 #907

- README.md
(cherry picked from commit a3ff6d10d11330fb66a19fd8ae7cf842002478fa)
Please review #913
> [5.5.1]update dependency version #913

- README.md
> [5.4.2]update dependency version #913

- README.md
> update dependency version #913

- README.md
> fix to 5.5.1.RELEASE #913

- .travis.yml
> Drop Oracle JDK from Travis CI #923

- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/pagination/PaginationInfoTest.java
- terasoluna-gfw-parent/pom.xml
> Upgrade Spring Boot 2.2.0.RELEASE #925 Apply Spring Data Commons 2.2 #926

- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/resources/org/terasoluna/gfw/common/codelist/ExistInCodeListTest-context.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/resources/org/terasoluna/gfw/common/codelist/i18n/simpleI18nCodeList.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/resources/org/terasoluna/gfw/common/exception/ResultMessagesLoggingInterceptorTest.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/resources/test-context.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/src/test/resources/test-context.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/resources/org/terasoluna/gfw/web/codelist/CodeListInterceptorTest.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/resources/test-context.xml
> replace schema location for spring from http to https

- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/src/main/java/org/terasoluna/gfw/web/pagination/PaginationTag.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/src/main/resources/META-INF/terasoluna.tld
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/src/test/java/org/terasoluna/gfw/web/pagination/PaginationTagTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/pagination/PaginationInfo.java
Please review #928.
**I think that this may be added from 5.4 series.**
> add innerElementClass attribute to pagination tag. #928

- terasoluna-gfw-parent/pom.xml
> update self defined libraries #933

- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/sequencer/JdbcSequencerTest.java
- terasoluna-gfw-parent/pom.xml
> Upgrade Spring Boot 2.2.2.RELEASE #935

- terasoluna-gfw-parent/pom.xml
> add dependency of java mail #945

- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/pagination/PaginationInfoTest.java
Please review https://github.com/terasolunaorg/terasoluna-gfw/pull/927#discussion_r352407134 .
> not use static import that not needed #925

- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> remove log4jdbc-remix #947

- terasoluna-gfw-parent/pom.xml
> Exclude javax.activation:activation and add com.sun.activation:javax.activation 1.2.0 #945

- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-parent/pom.xml
> Upgrade to hamcrest 2.x #950

- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/sequencer/JdbcSequencerTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/resources/org/terasoluna/gfw/common/codelist/ExistInCodeListTest-context.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/resources/org/terasoluna/gfw/common/codelist/i18n/simpleI18nCodeList.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/resources/org/terasoluna/gfw/common/exception/ResultMessagesLoggingInterceptorTest.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/resources/test-context.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/src/test/resources/test-context.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/el/ObjectToMapConverter.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/el/ObjectToMapConverterTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/pagination/PaginationInfoTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/resources/org/terasoluna/gfw/web/codelist/CodeListInterceptorTest.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/resources/test-context.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
Reverts terasolunaorg/terasoluna-gfw#957
> Revert "from Development/5.6.0"

- terasoluna-gfw-parent/pom.xml
> Upgrade Spring Boot 2.2.4.RELEASE #963

- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/src/main/java/org/terasoluna/gfw/common/codepoints/CodePoints.java
> resolve using deprecated method at CodePoints. #965

- terasoluna-gfw-parent/pom.xml
> remove commons file upload #972

- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
> remove exclude XML APIs #979

- terasoluna-gfw-parent/pom.xml
> remove javax.mail #945 #975

- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
> exclude javax.activation-api, dependecy jakarta.activation-api #980

- terasoluna-gfw-parent/pom.xml
This reverts commit 66a7d65e72759809ffbe91edadeae420f8fbac90.
Please review #976 .
> Continue to support Commons FileUpload #976

- README.md
- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-core-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> update 5.7.0-SNAPSHOT #985

- README.md
- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-core-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> update 5.6.1-SNAPSHOT #985

- README.md
> fix travis, coveralls URL to 5.6.x #985

- terasoluna-gfw-parent/pom.xml
> apply mybatis 3.5.5, mybatis-spring 2.0.5 #997

- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/src/main/resources/ContributorValidationMessages_en.properties
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/src/main/resources/ContributorValidationMessages_ja.properties
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/src/test/java/org/terasoluna/gfw/common/codepoints/validator/ConsistOfValidatorTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/resources/ContributorValidationMessages_en.properties
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/resources/ContributorValidationMessages_ja.properties
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/codelist/ExistInCodeListTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/main/resources/ContributorValidationMessages_en.properties
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/main/resources/ContributorValidationMessages_ja.properties
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/AbstractConstraintsTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/ByteMaxTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/ByteMinTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/ByteSizeTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/CompareTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/ContributorValidationMessagesJaTest.java
Please review #996 .
Please See also https://github.com/terasolunaorg/terasoluna-gfw/issues/996#issuecomment-684596239.
> provide ContributorValidationMessages_ja.properties #996

- terasoluna-gfw-parent/pom.xml
> apply spring-security-oauth2 2.5.0 #1002

- terasoluna-gfw-parent/pom.xml
> apply spring boot 2.4.0-M3 #989

- terasoluna-gfw-parent/pom.xml
> apply spring boot 2.4.0-M4 #989

- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraints/Compare.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/CompareTest.java
> Compare support Bean Validation 2.0 #1013

- terasoluna-gfw-parent/pom.xml
> apply spring boot 2.4.0-RC1 #989

- terasoluna-gfw-parent/pom.xml
> apply spring boot 2.4.0 #989

- terasoluna-gfw-parent/pom.xml
> Update Hibernate ORM 5.4.24.Final #1023

- terasoluna-gfw-parent/pom.xml
Please review #1023.
Correspondence of the following comments.
https://github.com/terasolunaorg/terasoluna-gfw/pull/1024#pullrequestreview-535232986
> Add entity manager version control and Annotation comment #1023

- terasoluna-gfw-parent/pom.xml
Please review #1023.
We also respond to these comments.
https://github.com/terasolunaorg/terasoluna-gfw/pull/1029#discussion_r534670258
> Update hibernate version to 5.4.25

- terasoluna-gfw-parent/pom.xml
> apply mybatis 3.5.6, mybatis-spring 2.0.6

- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/message/ResultMessages.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/message/StandardResultMessageType.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/message/ResultMessagesTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/message/StandardResultMessageTypeTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/src/main/java/org/terasoluna/gfw/web/pagination/PaginationTag.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/src/main/resources/META-INF/terasoluna.tld
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/src/test/java/org/terasoluna/gfw/web/pagination/PaginationTagTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/pagination/PaginationInfo.java
> make the tag library compatible with Bootstrap v4 #1008

- terasoluna-gfw-parent/pom.xml
Please review #1028.
A modified version of hibernate for #1024 and #1025 .
> Update Hibernate ORM 5.3.20.Final #1028

- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/codelist/i18n/SimpleI18nCodeListTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/date/DefaultClassicDateFactoryTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/exception/BusinessExceptionTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/resources/org/terasoluna/gfw/common/codelist/i18n/simpleI18nCodeList.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/download/FileDownloadViewTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/logging/TraceLoggingInterceptorController.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/logging/TraceLoggingInterceptorTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/token/TokenStringGeneratorTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/token/transaction/HttpSessionTransactionTokenStoreTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenInterceptorTest.java
Please review #1035.
PR check of coveralls not successful. But actual coverage of it has bean increased from master.
Please see https://coveralls.io/github/terasolunaorg/terasoluna-gfw?branch=master
> increase coverage verified with Coveralls #1035

- terasoluna-gfw-parent/pom.xml
Please review #1040.
It is a back port that summarizes the following PR.
#1024 , #1025 , #1030
> [5.6.x] Update Hibernate ORM 5.4.25.Final #1040

- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> depend jakarta lib. #1038

- terasoluna-gfw-parent/pom.xml
Please review #1042.
Reverted #1024, #1030 (#1023), because these contained in spring boot 2.4.1.
> apply spring boot 2.4.1 #1042

- README.md
Please review #1049
Confirmation method:
- Grep search for "5.6.0." and confirm that there are no omissions.
> update 5.6.1.RELEASE in README #1049

- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-core-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
Please review #1047
Confirmation method:
- Grep search for "5.6.1" and confirm that there are no omissions.
> update 5.6.2-SNAPSHOT #1047

- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-core-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> update 5.5.3-SNAPSHOT #1053

- terasoluna-gfw-parent/pom.xml
Reverts terasolunaorg/terasoluna-gfw#1056
> Revert "[5.6.x]Update the plugin version of terasoluna-gfw-parent #1010 (#1020)"

- terasoluna-gfw-parent/pom.xml
> apply joda-time 2.10.9 #1059

- terasoluna-gfw-parent/pom.xml
> spring boot 2.2.12 #1046

- terasoluna-gfw-parent/pom.xml
> Set doclint of maven-javadoc-plugin to none #1061

- .gitignore
Please review #1065 .
Removed unnecessary settings from gitignore.
> Remove unnecessary settings from gitignore #1065

- .gitignore
(cherry picked from commit b8541eb59cf37bc38386090aec3b9ae6fd81ff6f)
Please review #1067 .
Removed unnecessary settings from gitignore.
> [5.6.x]Remove unnecessary settings from gitignore #1065 (#1066)

- README.md
> update 5.7.0.RELEASE in README.md #1070

- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-core-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> update to 5.8.0-SNAPSHOT. #1074

- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-core-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> update to 5.6.3-SNAPSHOT. #1076

- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/src/main/java/org/terasoluna/gfw/web/pagination/PaginationTag.java
Please review #1079
confirm method:
- Confirm that `mvn clean install` succeeds.
- Confirm that GitLab job succeeds.
- Confirmed that there are no more indications about `PaginationTag` on SonarQube.
> [5.7.x] fix sonarqube point out #1069

- terasoluna-gfw-parent/pom.xml
> update boot version to 2.5.3 #1088

- .travis.yml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/ContributorValidationMessagesJaTest.java
> [5.7.x] fix license-maven-plugin setteing #1089

- terasoluna-gfw-parent/pom.xml
(cherry picked from commit 1afa2a4ff7cd78d22a6779f77d27b423fd460bbf)
Please review #1098.
> [5.7.x]update boot version to 2.5.3 #1088

- terasoluna-gfw-parent/pom.xml
(cherry picked from commit 8f5004871147cdd1ef19f3a310ce9942ece88c97)
Please review #1102.
> Apply Spring Boot 2.6.0-M3 #1100

- terasoluna-gfw-parent/pom.xml
> Apply Spring Boot 2.6.0-RC1 #1104

- terasoluna-gfw-parent/pom.xml
> update MyBatis version to 3.5.7 #1109

- terasoluna-gfw-parent/pom.xml
> update jakarta-inject version to 1.0.5 #1110

- terasoluna-gfw-parent/pom.xml
> update poi-ooxml version to 4.1.2 #1111

- terasoluna-gfw-parent/pom.xml
> update Google Guava version to 30.1.1-jre #1112

- terasoluna-gfw-parent/pom.xml
> update bouncycastle version to 1.69 #1113

- terasoluna-gfw-parent/pom.xml
> update commons-io version to 2.11.0 #1114

- terasoluna-gfw-parent/pom.xml
> update dozer to 6.5.2 #998

- terasoluna-gfw-parent/pom.xml
> Apply Spring Boot 2.6.0 #1108

- terasoluna-gfw-parent/pom.xml
(cherry picked from commit ef2e4dc556372031bbb97405f65ade5cc4483caf)
Please review #1134
> [5.7.x] update dozer to 6.5.2 #998

- terasoluna-gfw-parent/pom.xml
(cherry picked from commit e07562a3a421c8c5c316179138017ca4ffbf7e26)
Please review #1138.
> Apply Spring Boot 2.6.0 #1108 #1138

- terasoluna-gfw-parent/pom.xml
> Apply Spring Boot 2.6.1 #1137

- terasoluna-gfw-parent/pom.xml
(cherry picked from commit b85dd561be7564a3dd2417eec4bf545a1e175ef6)
Please review #1141.
> Apply Spring Boot 2.6.1 #1137 #1141

- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/resources/logback.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/src/test/resources/logback.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/src/test/resources/logback.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/resources/logback.xml
> changed log format #1143

- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/resources/logback.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/src/test/resources/logback.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/src/test/resources/logback.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/resources/logback.xml
(cherry picked from commit e850b77145da17084ea8947c74a5ce014d4aff68)
Please review #1145
> [5.7.x] changed log format #1143

- terasoluna-gfw-parent/pom.xml
> remove dependency spring-security-oauth2. #1147

- terasoluna-gfw-parent/pom.xml
(cherry picked from commit 9105829a752c905d87ee6f6447ae72d6747d486a)
Please review #1149 .
> [5.7.x]remove dependency spring-security-oauth2. #1147

- terasoluna-gfw-parent/pom.xml
> update dependency version of commons-compress. #1151

- terasoluna-gfw-parent/pom.xml
(cherry picked from commit 555dc21af075798640d7314f4363af335007c25c)
Please review #1153 .
> update dependency version of commons-compress. #1152

- README.md
> remove build status, coverage status. #1155

- README.md
> remove build status, coverage status. #1157

- README.md
- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-core-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> update SNAPSHOT to 5.7.2 #1159

- README.md
> Change the version in README to the latest version #1161

- .github/ISSUE_TEMPLATE/3-backport-issue.md
> improved backport-issue template #1164

- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/src/test/resources/logback.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/logging/TraceLoggingInterceptorTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/resources/logback.xml
> remove logback db

- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/logging/TraceLoggingInterceptorTest.java
(cherry picked from commit da9247a60c1a7a42163ddb7b3ad76e6459f1c715)
Please review #1170.
> Delete unnecessary import statements #1168

- terasoluna-gfw-parent/pom.xml
> Update Spring Boot version to 2.7.0 #1174

- terasoluna-gfw-parent/pom.xml
> Update Guava version #1176

- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
> add profile for jdk17 #1178

- terasoluna-gfw-parent/pom.xml
> Apply Spring Boot 2.7.3 #1185

- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> changed dozer to mapstruct #1183

- terasoluna-gfw-parent/pom.xml
(cherry picked from commit 67a12dc4e576117ba3812b3dd506cc4b1776e572)
Please review #1189 .
> Update Guava version #1189

- terasoluna-gfw-parent/pom.xml
Please review #1183 
See https://github.com/terasolunaorg/terasoluna-gfw/issues/1183#issuecomment-1249027817
> added lombok version properties #1183

- terasoluna-gfw-parent/pom.xml
> Update the version of Logback and SLF4J #1191

- terasoluna-gfw-parent/pom.xml
Please review #1181.
Fixed because tomcat version update was escaped.
> update tomcat10 version. #1181

- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> deleted Tiles #1194

- terasoluna-gfw-parent/pom.xml
> apply mybatis3.5.11 mybatisspring2.1.0

- terasoluna-gfw-parent/pom.xml
> apply mybatis3.5.11 mybatisspring3.0.0

- terasoluna-gfw-parent/pom.xml
> update boot version to 2.7.6 #1200

- terasoluna-gfw-parent/pom.xml
Please review #1210.
* Spring Boot 3.0.0 to 3.0.1
* tomcat 10.0.22 to 10.1.4
> Spring Boot 3.0.0 to 3.0.1

- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> updated spring-boot and library version for 5.7.2 #1209

- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
> remove dependecy joda-time in recommended. #1187

- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-parent/pom.xml
Please review https://github.com/terasolunaorg/terasoluna-gfw/issues/1216 .
> updated libraries and plugins for 5.8.0 #1216

- terasoluna-gfw-common-libraries/pom.xml
Please review https://github.com/terasolunaorg/terasoluna-gfw/issues/1207#issuecomment-1437951390 .
> update surefire version #1207

- terasoluna-gfw-common-libraries/terasoluna-gfw-string/src/main/java/org/terasoluna/gfw/common/fullhalf/DefaultFullHalf.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/src/test/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenTagTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/logging/TraceLoggingInterceptor.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/download/FileDownloadViewTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/exception/ExceptionLoggingFilterTest.java
Please review #1228 
- DefaultFullHalf.java
- Fixed full-width spaces to be escaped.
- TraceLoggingInterceptor.java
- Refactor if statements to combine "return true" into one.
- TransactionTokenTagTest.java, FileDownloadViewTest.java, ExceptionLoggingFilterTest.java
- The mock exception setting was moved out of assertThrows.
> corrected SonarQube point #1228

- terasoluna-gfw-parent/pom.xml
> update tomcat version to 10.1.7 #1232

- terasoluna-gfw-parent/pom.xml
> [5.7.x] update tomcat version to 9.0.73 #1234

- terasoluna-gfw-common-libraries/pom.xml
> Do not skip javadoc generation.

- README.md
- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-core-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> update SNAPSHOT to 5.8.1. #1238

- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/ByteSizeTest.java
> Correct the number of digits in the format string of the argument of String#format #1241

- README.md
- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-core-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> update 5.9.0-SNAPSHOT. #1243

- terasoluna-gfw-parent/pom.xml
> update cargo-maven3-plugin version #1246

- README.md
- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-core-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
Please review #1248 
relate to https://terasolunaorg.atlassian.net/browse/TSF4J5-2391
> update 5.7.3-SNAPSHOT. #1248

- README.md
- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-core-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
Please review #1245 .
https://terasolunaorg.atlassian.net/browse/TSF4J5-2391
> update 5.8.2-SNAPSHOT #1245

- terasoluna-gfw-parent/pom.xml
> update boot version 3.0.1 to 3.1.0 #1251

- terasoluna-gfw-parent/pom.xml
Please review https://github.com/terasolunaorg/terasoluna-gfw/issues/1254.
relates to https://terasolunaorg.atlassian.net/browse/TSF4J5-2965.
> update boot version to 2.7.12 #2965

- terasoluna-gfw-parent/pom.xml
> update boot version 3.1.0 to 3.1.1 #1255

- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/resources/test-context.xml
Please review #1257 .
Added @EnableAspectJAutoProxy to enable AOP in JavaConfig version. So I added an equivalent definition to the XML as well.
JIRA
Added aspectj-autoproxy to test-context.xml to enable AOP definition in ResultMessagesLoggingInterceptorTest.xml.
https://terasolunaorg.atlassian.net/browse/TSF4J5-3061
> Added aop:aspectj-autoproxy according to JavaConfig definition. #1257

- terasoluna-gfw-parent/pom.xml
Please review #1264.
relates to [TSF4J5-3567](https://terasolunaorg.atlassian.net/browse/TSF4J5-3567).
> [5.7.x] update boot version 2.7.14 to 2.7.15 #1264

- terasoluna-gfw-parent/pom.xml
> Apply Spring Boot 2.7.18 #1266

- terasoluna-gfw-parent/pom.xml
Please review #1263
relates to https://terasolunaorg.atlassian.net/browse/TSF4J5-3810
> update boot version 3.1.1 to 3.2.0 #1263

- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/codelist/SimpleMapCodeListTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/src/test/java/org/terasoluna/gfw/common/date/jodatime/JdbcFixedJodaTimeDateFactoryTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/AbstractConstraintsTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/src/test/java/org/terasoluna/gfw/web/pagination/PaginationTagTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/codelist/CodeListInterceptorTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/logging/TraceLoggingInterceptorTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenContextHandlerMethodArgumentResolverTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenContextImplTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenInfoTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenInterceptorTest.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenTest.java
- Remove unnecessary import statements.
- Correct copy and paste errors.
Please review #1269.
> Remove unnecessary import statements. Correct copy and paste errors. #1269

- terasoluna-gfw-parent/pom.xml
Please review #1272 
The version of the master cargo-maven3-plugin was not up to date in #1246, it is addressed in this Issue.
relates to https://terasolunaorg.atlassian.net/browse/TSF4J5-3938
> library version up #1272

- terasoluna-gfw-parent/pom.xml
Please review #1275.
relates to [TSF4J5-4080](https://terasolunaorg.atlassian.net/browse/TSF4J5-4080).
> update boot version 3.2.0 to 3.2.2 #1275

- terasoluna-gfw-parent/pom.xml
Please review https://github.com/terasolunaorg/terasoluna-gfw/issues/1272#issuecomment-1916557099 .
> Remove logback and slf4j to make them dependent on spring-boot #1272

- terasoluna-gfw-parent/pom.xml
Please review #1278
relates to https://terasolunaorg.atlassian.net/browse/TSF4J5-3950
> [5.7.x] library version up #1278

- terasoluna-gfw-parent/pom.xml
> [5.7.x] delete commons-fileupload #1285

- terasoluna-gfw-common-libraries/pom.xml
Please review #1287.
relates to [rowse/TSF4J5-4137](https://terasolunaorg.atlassian.net/browse/TSF4J5-4137).
> jacoco version up. #1287

- terasoluna-gfw-parent/pom.xml
Please review https://github.com/terasolunaorg/terasoluna-gfw/issues/1272#issuecomment-1933454902
relates to https://terasolunaorg.atlassian.net/browse/TSF4J5-4119?focusedCommentId=13489
> slf4j-api version up #1272

- terasoluna-gfw-parent/pom.xml
Please review #1278.
relates to [TSF4J5-4119](https://terasolunaorg.atlassian.net/browse/TSF4J5-4119).
> slf4j-api version up #1278

- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
> Change JAXB artifacts from org.glassfish.jaxb to com.sun.xml.bind #1292

- README.md
Please review #1295 .
Related to https://terasolunaorg.atlassian.net/browse/TSF4J5-4265 .
> update guideline link. #1295

- README.md
Please review #1297 .
Related to https://terasolunaorg.atlassian.net/browse/TSF4J5-4267
> [5.8.x]update guideline link. #1297

- README.md
- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-core-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
Please review https://github.com/terasolunaorg/terasoluna-gfw/issues/1302
Related to https://terasolunaorg.atlassian.net/browse/TSF4J5-4332
> update 5.10.0-SNAPSHOT. #1302

- README.md
- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-core-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
Please review https://github.com/terasolunaorg/terasoluna-gfw/issues/1304 .
Related to https://terasolunaorg.atlassian.net/browse/TSF4J5-4375
> [5.9.x]update 5.9.1-SNAPSHOT. #1304

- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/logging/TraceLoggingInterceptorTest.java
(cherry picked from commit 0efffa8c798aff561f52e1d044e13395cea1fe9e)
Please review #1312
relates to https://terasolunaorg.atlassian.net/browse/TSF4J5-4589
> fixed @Ignore tests #1309

- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/resources/logback.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/src/test/resources/logback.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/src/test/resources/logback.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/resources/logback.xml
Please review #1308.
Related to https://terasolunaorg.atlassian.net/browse/TSF4J5-4092
> fix logback settings #1308

- terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/resources/logback.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/src/test/resources/logback.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/src/test/resources/logback.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/resources/logback.xml
(cherry picked from commit 310aac52f372d7f5d3800e3dda29ac742f708148)
Please review #1314 .
Related to https://terasolunaorg.atlassian.net/browse/TSF4J5-4347
> [5.7.x]fix logback settings #1308

- terasoluna-gfw-parent/pom.xml
Please review #1316 
relate to https://terasolunaorg.atlassian.net/browse/TSF4J5-4593
> apply Spring Boot Dependencies 3.3.0-RC1. #1316

- terasoluna-gfw-parent/pom.xml
Please review #1318 .
relate to https://terasolunaorg.atlassian.net/browse/TSF4J5-4694
>  apply Spring Boot Dependencies 3.3.0. #1318

- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/exception/SystemExceptionResolver.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/exception/SystemExceptionResolverTest.java
> added options to SystemExceptionResoluver #1320

- terasoluna-gfw-parent/pom.xml
Please review #1323 .
relate to https://terasolunaorg.atlassian.net/browse/TSF4J5-4780 .
> update spring-boot 3.3.1. #1323

- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/exception/SystemExceptionResolverTest.java
Please review https://github.com/terasolunaorg/terasoluna-gfw/issues/1320#issuecomment-2196142219
Added test when both of the two options added in #1320 are true.
> added test when checkCause and checkSubCalss are both true #1320

- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/exception/SystemExceptionResolver.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/exception/SystemExceptionResolverTest.java
Please review #1326
https://terasolunaorg.atlassian.net/browse/TSF4J5-4812
> added options to SystemExceptionResoluver #1326

- terasoluna-gfw-parent/pom.xml
Please review #1332
relate to https://terasolunaorg.atlassian.net/browse/TSF4J5-4917
> Apply Spring Boot 3.4.0-M1 #1332

- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/el/Functions.java
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/el/FunctionsTest.java
Please review #1336 .
Corresponding backport of f:link modifications
JIRA
https://terasolunaorg.atlassian.net/browse/TSF4J5-4953
> [5.7.x] Reviewed the characters allowed in f:link. #1336 #TSF4J5-4953

- terasoluna-gfw-parent/pom.xml
Please review #1338 
relate to https://terasolunaorg.atlassian.net/browse/TSF4J5-5121
> apply spring boot 3.4.0-M2. #1338

- terasoluna-gfw-parent/pom.xml
> update cargo.container.url #1340

- terasoluna-gfw-parent/pom.xml
> update cargo.container.url #1342

- terasoluna-gfw-parent/pom.xml
> Spring 5 series final version upgrade #1344 #TSF4J5-4975

- terasoluna-gfw-parent/pom.xml
Please review #1346
relate to https://terasolunaorg.atlassian.net/browse/TSF4J5-5281
> apply Spring Boot 3.4.0-M3 #1346

- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-core-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> add <developers> and <scm> on pom.xml #1352

- terasoluna-gfw-parent/pom.xml
Please review #1355 
relate to https://terasolunaorg.atlassian.net/browse/TSF4J5-5354
> apply Spring Boot 3.4.0-RC1 #1355

- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-core-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> [5.7.x] Need to override <developers> and <scm> on pom.xml #1358

- terasoluna-gfw-parent/pom.xml
Please review https://github.com/terasolunaorg/terasoluna-gfw/issues/1360
relates to [TSF4J5-5537](https://terasolunaorg.atlassian.net/browse/TSF4J5-5537).
> update spring boot v3.4.0. #1360

- terasoluna-gfw-parent/pom.xml
Please review #1366 
relates to [TSF4J5-5599](https://terasolunaorg.atlassian.net/browse/TSF4J5-5599).
> update spring boot 3.4.1. #1366

- terasoluna-gfw-parent/pom.xml
Please review #1368 
relates to [TSF4J5-5555](https://terasolunaorg.atlassian.net/browse/TSF4J5-5555)
> added dependency on terasoluna-dependencies and removed unnecessary library definitions. #1368

- terasoluna-gfw-parent/pom.xml
Please review https://github.com/terasolunaorg/terasoluna-gfw/issues/1368#issuecomment-2562033608
> setting snapshot repository. #1368

- terasoluna-gfw-parent/pom.xml
(cherry picked from commit 67a133579445cd18f8a8b197550c050353d8ce82)
Please review https://github.com/terasolunaorg/terasoluna-gfw/issues/1370#issuecomment-2562035790
> [5.7.x]setting snapshot repository. #1370

- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
Please review #1374.
relates to [TSF4J5-5764](https://terasolunaorg.atlassian.net/browse/TSF4J5-5764).
> remove tomcat-jsp-api. #1374

- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
Please review #1375.
relates to [TSF4J5-5766](https://terasolunaorg.atlassian.net/browse/TSF4J5-5766).
> [5.7.x] remove tomcat-jsp-api. #1375

- README.md
- terasoluna-gfw-parent/pom.xml
Please review #1383 
relates to [TSF4J5-5557](https://terasolunaorg.atlassian.net/browse/TSF4J5-5557)
> [5.7.x]remove the snapshot repository settings from pom.xml. #1383

- terasoluna-gfw-parent/pom.xml
Please review #1386.
relates to [TSF4J5-5994](https://terasolunaorg.atlassian.net/browse/TSF4J5-5994).
> [5.7.x] maven-dependency-plugin 3.2.0 to 3.8.1. #1386, TSF4J5-5994

- README.md
- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-core-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> 5.11.0-SNAPSHOT. #1390

- README.md
- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-core-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> 5.10.1-SNAPSHOT. #1391

- README.md
- pom.xml
- terasoluna-gfw-common-libraries/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
- terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
- terasoluna-gfw-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-core-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
- terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
- terasoluna-gfw-parent/pom.xml
> 5.7.5-SNAPSHOT. #1392

- terasoluna-gfw-parent/pom.xml
> [5.7.x]update terasoluna-dependencies 1.0.1-SNAPSHOT #1392

- terasoluna-gfw-parent/pom.xml
> [5.10.x]update terasoluna-dependencies 2.0.1-SNAPSHOT #1391

- terasoluna-gfw-parent/pom.xml
> update terasoluna-dependencies 3.0.0-SNAPSHOT #1390
