.travis.yml

(cherry picked from commit ba9292ddd9ef70d28b46b65f7fbce464d3e00d82)
Please review #290 .

[5.0.x] #290: Support Oracle JDK8 as new build environment on travis

---

terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/date/DateConvertUtils.java

(cherry picked from commit 52bff3130f5467ca0938cb0f5be13ba989b149b9)
Please review #310 .

[5.0.x] #310: Fix typo in private constant of DateConvertUtils

---

terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/message/MessagesPanelTag.java

(cherry picked from commit c2000fb7de25563531589627d060c51622a7244c)
Please review #264 .

[5.0.x] #264: fix typo in javadoc of MessagesPanelTag

---

terasoluna-gfw-parent/pom.xml
terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/pagination/PaginationInfoTest.java

Failed test cases at the Spring IO Platform 1.1.3 are follows:
* PaginationInfoTest#testIsLastPage_NotLast
* PaginationInfoTest#testGetBeginAndEnd_LastPageGreaterThanCurrentEnd
* PaginationInfoTest#testGetBeginAndEnd_CurrentEndGreaterThanLastPage
The error cause is https://jira.spring.io/browse/DATACMNS-713. But root cause is implementation of our test case scenarios and test data. (Probably,modifications of DATACMNS-713 is not problem)
Therefore I've modified some test cases via 815a1d724b1d620ae2814af230bc4dd46ba20ee5.
Please review #315 .

#315: Update to Spring IO Platform 1.1.3

---

terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/CompareValidator.java
terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/ConstraintValidatorsUtils.java
terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/InternalValidatorForChronoLocalDate.java
terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/InternalValidatorForChronoLocalDateTime.java
terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/InternalValidatorForChronoZonedDateTime.java
terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/InternalValidatorForDate.java
terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/InternalValidatorForLocalTime.java
terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/InternalValidatorForOffsetDateTime.java
terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/InternalValidatorForOffsetTime.java
terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/InternalValidatorForYear.java
terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/InternalValidatorForYearMonth.java

I've polished some source codes.
* Change method name : `getProperty` -> `getPropertyValue`
* Change method argument variable name : `value` -> `bean`
* Change method of creating a `DateTimeFormatter` for "Date and Time(JSR-310)"  : timing of `withResolverStyle` method calling
* Remove unnecessary argument on getter method invocation : `getter.invoke(value, (Object[]) null);` -> `getter.invoke(value);`
* Apply a code formatter using `mvn formatter:format`
* Fix a typo in javadoc

Polishing #372

---

terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraints/Compare.java
terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/CompareValidator.java
terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/CompareTest.java

I've refactor Node enum.
I think `RIGHT`(`RIGHT_PROPERTY`) is unnecessary option.
If want to bind to right property, it can be realized by reversing left and right.
Hence, i've removed `RIGHT`(`RIGHT_PROPERTY`).
**Note:**
At first, please review #413.

Remove RIGHT_PROPERTY from Node #372

---

terasoluna-gfw-parent/pom.xml

* Apply fix version for CVE-2015-5211
Please review #391 .
**Note:**
CI of functional tests and Sample application has been succeeded using Spring 3.2.16.
* https://travis-ci.org/terasolunaorg/terasoluna-gfw-functionaltest/builds/97594180
* https://travis-ci.org/terasolunaorg/terasoluna-tourreservation/builds/97597601

Update to Spring 3.2.16.RELEASE #391

---

terasoluna-gfw-parent/pom.xml

* Apply fix version for CVE-2015-5211
* Apply fix version for COLLECTIONS-580
Please review #392 .
**Note:**
CI of functional tests and sample application has been succeeded using Spring IO Platform 1.1.5.
* https://travis-ci.org/terasolunaorg/terasoluna-gfw-functionaltest/builds/97815198
* https://travis-ci.org/terasolunaorg/terasoluna-tourreservation/builds/97815484
* https://travis-ci.org/terasolunaorg/terasoluna-tourreservation-mybatis3/builds/97816329

Update to Spring IO Platform 1.1.5 #392

---

terasoluna-gfw-parent/pom.xml

I supported tomcat 8 only and removed tomcat7-maven-plugin.
If tomcat 7 or other application server to be used, it need to override some properties(`cargo.container.id`, `cargo.container.url`) as below:
1. Override using `pom.xml` as below  (recommended)
```xml
<cargo.container.id>tomcat7x</cargo.container.id>
<cargo.container.url>http://archive.apache.org/dist/tomcat/tomcat-7/v${cargo.tomcat7.version}/bin/apache-tomcat-${cargo.tomcat7.version}.zip</cargo.container.url>
<cargo.tomcat7.version>7.0.67</cargo.tomcat7.version>
```
2. Override using system properties(`-D` option) as below
```console
mvn cargo:run -Dcargo.container.id=tomcat7x -Dcargo.container.url=http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.67/bin/apache-tomcat-7.0.67.zip
```
Please review #451 .

Support cargo-maven2-plugin instead of tomcat7-maven-plugin #451

---

CONTRIBUTING.md

Please review #386.
(cherry picked from commit 59c4f53dfb807348b9214cba8344ac13be3f8e33)

[1.0.x] Fix a rule for git commit comments #386

---

CONTRIBUTING.md

Please review #386.
(cherry picked from commit 59c4f53dfb807348b9214cba8344ac13be3f8e33)

[5.0.x] Fix a rule for git commit comments #386

---

terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraints/ByteMax.java
terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraints/ByteMin.java
terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraints/Compare.java

Sorry, I've added missing javadoc in `terasoluna-gfw-validator` constraint annotations.
Please, review #372.

add missing javadoc in constraint annotations #372

---

terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenContext.java
terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenContextImpl.java

Please review #593 .
Cherry-picked from #594 .

[5.1.x] TransactionTokenContext deprecated. #593

---

terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenInterceptor.java
terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenInterceptorTest.java

Please review #564.
(cherry picked from commit 851cab172ac72a671e65a98bb1f2e006dae557d9)

[5.1.x] Fix TransactionTokenInterceptor throws NPE when an Exception is thrown in preHandle. #564

---

README.md

modify readme.md about pom polishing #508

---

.travis.yml

(cherry picked from commit 2bf60c0d4361ae936fdaf8adc18ee1cab36f194d)
Please review #666.

[5.2.x]Drop oraclejdk7 from .travis.yml #666

---

.travis.yml

(cherry picked from commit 2bf60c0d4361ae936fdaf8adc18ee1cab36f194d)
Please review #666.

[5.1.x]Drop oraclejdk7 from .travis.yml #666

---

.travis.yml

[5.0.x]Drop oraclejdk7 and openjdk6 from ".travis.yml". #666 and #725

---

terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/exception/ResultMessagesNotificationException.java

5.3.x backported, please confirm. #701

[5.3.x]Modify misprints in Javadoc #701

---

.travis.yml
terasoluna-gfw-common-libraries/pom.xml
terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/exception/ExceptionLoggerTest.java
terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/exception/ResultMessagesLoggingInterceptorTest.java
terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/src/test/java/org/terasoluna/gfw/web/message/MessagesPanelTagTest.java
terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/src/test/java/org/terasoluna/gfw/web/pagination/PaginationTagTest.java
terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/el/Functions.java
terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/codelist/CodeListInterceptorTest.java
terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/el/FunctionsTest.java
terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/exception/HandlerExceptionResolverLoggingInterceptorTest.java
terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/logging/HttpSessionEventLoggingListenerTest.java
terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/mvc/support/CompositeRequestDataValueProcessorTest.java
terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/pagination/PaginationInfoTest.java
terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenInterceptorTest.java
terasoluna-gfw-parent/pom.xml

Please review #810
1. Change version to spring io platform Cairo-SR1
------------------------------------------------------
・terasoluna-gfw-parent/pom.xml 
<io.spring.platform.version> : Cairo-SR1
<jadira-usertype-core.version> : 6.0.1.GA
java-version : 1.8
<cargo.tomcat9.version> : 9.0.6
・terasoluna-gfw-common-libraries/pom.xml 
java-version : 1.8
2. Fix build error of UriUtils
------------------------------------------------------
・Error contents
[ERROR] /home/travis/build/terasolunaorg/terasoluna-gfw/terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/el/Functions.java:[180,11] exception java.io.UnsupportedEncodingException is never thrown in body of corresponding try statement
https://travis-ci.org/terasolunaorg/terasoluna-gfw/jobs/391071386#L2025 …

[5.5.0.RC2]Upgrade to spring io platform Cairo-SR1. #810

---

terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml

Please review #736 .
fix as described in Issue.
After merging, do backport.

Move dependency jackson-datatype-joda to gfw-jodatime-dependencies #736

---

terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraints/ByteMin.java
terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraints/ByteSize.java
terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraints/Compare.java
terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/ByteMinValidator.java
terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/ByteSizeValidator.java
terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/AbstractConstraintsTest.java
terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/ByteMaxTest.java
terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/ByteMinTest.java
terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/ByteSizeTest.java
terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/test/resources/ValidationMessages.properties

(cherry picked from commit e3e85c040c72490e2600e032621c1f758e4ba58e)
Please review #761 .
Omit `ElementType.TYPE_USE` and `Repeatable` from ver5.5.1 (for Bean Validation 1.1).

[5.4.x] create @ByteSize validator #761

---

terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/src/main/java/org/terasoluna/gfw/common/codepoints/ConsistOf.java
terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/ExistInCodeList.java

Please review #857 .
This PR is backport review of `@Target` and more(improvement and **Not** compliant with Bean Validation 2.0 from #863 ) to 5.4.x .
(5.4.x branch will **not** be compliant with Bean Validation 2.0)

[5.4.x] Unify target of constraint annotations #857

---

terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/el/ObjectToMapConverter.java
terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/el/ObjectToMapConverterTest.java

fix convert of Boolean #846

---

.travis.yml

Cherry picked from commit 41c6c945bdbfae80d1e908ff7caf39ec4e07e1b8 .

[5.5.x] Drop Oracle JDK from Travis CI #923

---

.travis.yml

Added setting to use openjdk7.

[5.4.x] Fix Travis CI environment for Trusty #923

---

.travis.yml

Cherry picked from commit a6c161e082839ca615d413d7d48474faaa12f7d1 .

[5.3.x] Fix Travis CI environment for Trusty #923

---

.travis.yml

Cherry picked from commit 7b244285446ed5a1f7094f7b0989c2b8a413e08d .

[5.2.x] Fix Travis CI environment for Trusty #923

---

.travis.yml

Cherry picked from commit cb0f1760b3e1abacfd82db64c1b72b5d910034be .

[5.1.x] Fix Travis CI environment for Trusty  #923

---

.travis.yml

Cherry picked from commit 00dc1a8b1400c3f31b409d04304cd4cc1ef3e525 .

[5.0.x] Fix Travis CI environment for Trusty #923

---

.travis.yml

Cherry picked from commit dd3d0444c400d5fc0181ad24e83d583fd6cb9c60 .

[1.0.x] Fix Travis CI environment for Trusty #923

---

terasoluna-gfw-parent/pom.xml

Manage dependency Bouncy Castle Provider. #953

---

terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/date/DateConvertUtils.java
terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/src/test/java/org/terasoluna/gfw/web/pagination/PaginationTagTest.java

Please review #971.
3 out of 9 cases were modified.
-----
Modified
* `PaginationTagTest`
→ Test assertion added (Check for null and false after [release()](https://github.com/terasolunaorg/terasoluna-gfw/blob/f88f52b1e64be9ed19ce14299b8da400a4bb7bd7/terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/src/main/java/org/terasoluna/gfw/web/pagination/PaginationTag.java#L384) method execution)
* `PaginationTagTest`
→ Delete empty test (What has not changed since the [first commit](https://github.com/terasolunaorg/terasoluna-gfw/blob/2b360b3849adf4b4b11cb42ae2775c41a6184f3a/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/pagination/PaginationTagTest.java#L599))
* `DateConvertUtils`
→ Eliminate duplicate strings.
-----
As it is
* `PaginationTag`
→ Regarding the complexity of …

fix sonarqube point out #971

---

terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml

Please review #984 .
Grep with `mvn dependency: tree` and confirmed that there is no omission in exclusion.

exclude hibernate-entitymanager from jadira usertype.core #984

---

terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/src/test/java/org/terasoluna/gfw/common/codepoints/validator/ConsistOfValidatorJaTest.java
terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/src/test/java/org/terasoluna/gfw/common/codepoints/validator/ConsistOfValidatorTest.java
terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/codelist/ExistInCodeListJaTest.java
terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/codelist/ExistInCodeListTest.java

Please review #996.
In #1001, the test for Japanese was implemented in the existing test class. It was found that if the locale was changed for each test in 1 class, the locale would be changed at an unintended timing depending on the runtime environment. So I separated tests for different locales as a workaround.

separete tests for different locales #996

---

terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/exception/DefaultExceptionLevelResolver.java
terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/exception/ExceptionLogger.java
terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/exception/SimpleMappingExceptionCodeResolver.java
terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/src/main/java/org/terasoluna/gfw/web/message/MessagesPanelTag.java
terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/el/Functions.java
terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/el/ObjectToMapConverter.java
terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/pagination/PaginationInfo.java
terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionToken.java
terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenInfoStore.java

Please review #1015 .
* all of `StringUtils#isEmpty` -> `StringUtils#hasLength` or `StringUtils#hasText`
* a part of `str == null || str.isEmpty()` ->`StringUtils#hasLength` or `StringUtils#hasText`
- These depend on Spring Core but make their own decisions.
* a part of `collection == null || collection.isEmpty()` ->`CollectionUtils#isEmpty` or `StringUtils#hasText`
- These depend on Spring Core but make their own decisions.
* a part of `StringUtils#hasLength` -> `StringUtils#hasText`
- These don't make sense to handle whitespace.

resolve spring 5.3.0 deprecated StringUtils#isEmpty #1015

---

terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraints/Compare.java
terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/CompareTest.java

(cherry picked from commit 047bcf45510d30cafd66129a033cf3dc53ca0f1e)
Please review #1044
Conflicts have occurred for the following reasons:
- `org.junit.Assert.assertThat` was used instead of `org.hamcrest.MatcherAssert.assertThat` because #992 wasn't backported
->Since Spring Boot 2.4.0. Is not used in 5.6.x, I decided to use  `org.junit.Assert.assertThat` according to the original description.
- Class CompareTestForm wasn't static because #996 wasn't backported
->Since it doesn't have to be static, static is not used according to the original description.
Checklist:
- I ran CompareTest.java on eclipse and confirmed that everything was successful.
- Confirmed that it can be built with GitLab

Compare support Bean Validation 2.0 #1044

---

terasoluna-gfw-parent/pom.xml

Please review #1010.
Update the plugin version of terasoluna-gfw-parent.
Confirmation
- Confirmed that there is no Warning when building in GitLab.
- Confirmed that the upgrade of the plugin does not affect the operation.
- `maven-assembly-plugin`：Confirmed that there is no warning when running `mvn package`.
- `maven-clean-plugin`：Confirmed that the `target` directory is deleted when running `mvn clean install`.
- `maven-compiler-plugin`：Confirmed that there is no warning when running `mvn compile`.
- `maven-dependency-plugin`：Confirmed that no warning is printed when running `mvn dependency:tree`.
- `maven-deploy-plugin`：Confirmed that the gitlab job successfully pushes to the snapshot repository.
- `maven-install-plugin`：Confirmed that `mvn clean install` can add artifacts to the local …

Update the plugin version of terasoluna-gfw-parent #1010

---

terasoluna-gfw-parent/pom.xml

* Update the plugin version of terasoluna-gfw-parent #1010
* Update cargo-maven2-plugin to the latest version #1010
(cherry picked from commit bb42d67a4d0eed5da96c48ae2ae9a9712e80188d)
Please review https://github.com/terasolunaorg/terasoluna-gfw/issues/1055.
Confirmation
- I did a Grep search for `plugin` to see if there was any other place that managed the plugin version other than the place where I imported it with cherry-pick.
- Confirmed that there is no Warning when building in GitLab.
- Confirmed that the upgrade of the plugin does not affect the operation.
- `maven-assembly-plugin`：Confirmed that there is no warning when running `mvn package`.
- `maven-clean-plugin`：Confirmed that the `target` directory is deleted when running `mvn clean install`.
- …

[5.6.x]Update the plugin version of terasoluna-gfw-parent #1010 (#1020)

---

terasoluna-gfw-parent/pom.xml

Please review #1063 
Confirm that I can generate javadoc with maven javadoc: javadoc in each repository.

Set doclint of maven-javadoc-plugin to none and update maven-javadoc-plugin #1063

---

terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/src/main/java/org/terasoluna/gfw/web/pagination/PaginationTag.java

Please review #1069 
confirm method:
- Confirm that `mvn clean install` succeeds.
- Confirm that GitLab job succeeds.
- Confirmed that there are no more indications about `PaginationTag` on SonarQube.
I took the following actions:
- `PaginationTag`
Since similar processing appeared repeatedly, I cut it out in another method.
- `ObjectToMapConverter`
As stated in https://github.com/terasolunaorg/terasoluna-gfw/pull/974#issue-382818240, I found refactoring difficult.

fix sonarqube point out #1069

---

pom.xml
terasoluna-gfw-common-libraries/pom.xml
terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
terasoluna-gfw-dependencies/pom.xml
terasoluna-gfw-parent/pom.xml

Please review #1083
Confirmation is done with maven 3.8.1.
The changes other than the version upgrade are as follows:
- The latest version of coveralls-maven-plugin is 4.3.0, but since travis is currently unavailable, the version upgrade is on hold.
- Due to the version upgrade of formatter-maven-plugin, the format of javadoc comments will change, but #1084 will handle this.
- The `com.google.code:maven-license-plugin` has been changed to `com.mycila:license-maven-plugin` as in #600.
- Added settings required for importing private key in maven 3.8.1 to maven-gpg-plugin
- The maven-antrun-plugin should have been originally defined in terasoluna-gfw-parent, but it was defined in terasoluna-gfw-common-libraries and was not used by anyone, so I deleted it.
- When executing `mvn site`, a …

update the plugin version #1083

---

pom.xml
terasoluna-gfw-common-libraries/pom.xml
terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
terasoluna-gfw-dependencies/pom.xml
terasoluna-gfw-parent/pom.xml

Please review #1086
Confirmation is done with maven 3.8.1.
The changes other than the version upgrade are as follows:
- The latest version of coveralls-maven-plugin is 4.3.0, but since travis is currently unavailable, the version upgrade is on hold.
- Due to the version upgrade of formatter-maven-plugin, the format of javadoc comments will change, but #1084 will handle this.
- The `com.google.code:maven-license-plugin` has been changed to `com.mycila:license-maven-plugin` as in #600.
- In the process of GPG processing, I added a setting to maven-gpg-plugin to prevent GUI called pinentry that occurs when GPG version is 2.1 or higher.
- The maven-antrun-plugin should have been originally defined in terasoluna-gfw-parent, but it was defined in terasoluna-gfw-common-libraries and was not used …

[5.7.x] update the plugin version #1083

---

.travis.yml
terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/ContributorValidationMessagesJaTest.java

Please review #1089
I ran `mvn license:format -P common-libs` and fixed the file without the license header.

added license header #1089

---

terasoluna-gfw-common-libraries/pom.xml

Please review #1089
See:https://github.com/terasolunaorg/terasoluna-gfw/issues/1089#issuecomment-906922456
`<encoding>` is described in `<configuration>`, not in `<licenseSet>`.
I executed `mvn license:check` and confirmed the operation.

fix license-maven-plugin setteing #1089

---

terasoluna-gfw-parent/pom.xml

Please review #1196.
* Spring Boot 3.0.0-M4 to 3.0.0
* Temporary support will be removed as it is now supported by Spring Boot. 
#1192

Spring Boot 3.0.0-M4 to 3.0.0

---

terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
terasoluna-gfw-parent/pom.xml

Please consider to support `java-time-jsptags` #703 .
Date and Time API1 is a standard API provided by JDK, so I suggest not to separate libraries like `terasoluna-gfw-jsr310-*` #737.

support java-time-jsptags #703

---

terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
terasoluna-gfw-parent/pom.xml

Please review #1187.
The following are fixed
* Joda-Time version up
* Removed libraries (JSP Tag Library, Jadira Usertype) from dependencies that no longer work with the base version of Jakarta
* Joda-Time Factory provided by terasoluna-gfw has been deprecated

deprecated joda time

---

terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/date/DateConvertUtilsTest.java
terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/message/ResultMessageTest.java
terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/message/ResultMessageUtilsTest.java
terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/message/ResultMessagesTest.java
terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/query/QueryEscapeUtilsTest.java
terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/src/test/java/org/terasoluna/gfw/common/date/jodatime/AbstractJodaTimeDateFactoryTest.java
terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/src/test/java/org/terasoluna/gfw/common/date/jodatime/DefaultJodaTimeDateFactoryTest.java
terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/src/test/java/org/terasoluna/gfw/common/date/jodatime/JdbcAdjustedJodaTimeDateFactoryTest.java
terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/src/test/java/org/terasoluna/gfw/common/date/jodatime/JdbcFixedJodaTimeDateFactoryTest.java
terasoluna-gfw-common-libraries/terasoluna-gfw-string/src/test/java/org/terasoluna/gfw/common/fullhalf/DefaultFullHalfTest.java
terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraintvalidators/ConstraintValidatorsUtilsTest.java
terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/src/test/java/org/terasoluna/gfw/web/pagination/PaginationTagTest.java
terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/src/test/java/org/terasoluna/gfw/web/util/JspTagUtilsTest.java
terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/el/FunctionsTest.java
terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/util/HtmlEscapeUtilsTest.java

Please review #1222 
`SerializationUtils.deserialize()` is deprecated because it can cause RCE vulnerabilities.
However, the class used is a
- test class to see if classes implementing Serializable can be serialized and deserialized without exception.
- The target of deserialization is the test data prepared in the immediately preceding process, and we do not do anything to obtain the data from outside.
In addition, `SerializationUtils.deserialize()` is used as it is because no valid general library could be found.

fixed deprecated methods #1222

---

terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/resources/test-context.xml

Please review #1259.
Since the backport will be a version where JavaConfig doesn't exist yet, we only reflected the XML modifications.
JIRA
https://terasolunaorg.atlassian.net/browse/TSF4J5-3071

Backport:Added aop:aspectj-autoproxy according to JavaConfig definition. #1259

---

terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/logging/TraceLoggingInterceptorTest.java

Please review #1309
relatest to https://terasolunaorg.atlassian.net/browse/TSF4J5-1528
- testPostHandle_NormalLogOutput_ViewNotNull, testPostHandle_NormalLogOutput_ModelNull
- The test is left as it was determined that the test is to check for differences in the parameters to be set in `postHandle()`.
-  testPostHandle_NotStarted
- It was left as a test, but the name was modified because it was confusing.
- testPostHandle_NotHandler_Normal, testPostHandle_NotHandler_Warn
- Delete because the test failed and it is unclear what it was created for.

fixed @Ignore tests #1309

---

terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/el/Functions.java
terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/el/FunctionsTest.java

Please review #[1334](https://github.com/terasolunaorg/terasoluna-gfw/issues/1334).
Incorrect URL correspondence character in f:link has been corrected.
JIRA
https://terasolunaorg.atlassian.net/browse/TSF4J5-4951

Reviewed the characters allowed in f:link. #1334 #TSF4J5-4951

---

pom.xml
terasoluna-gfw-common-libraries/pom.xml
terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
terasoluna-gfw-dependencies/pom.xml
terasoluna-gfw-parent/pom.xml

Please review #1362 
- Removed xml-maven-plugin for formatting XML files in VSCode.
- The goal of maven-dependency-plugin, `sources`, has been deprecated and corrected to the appropriate value.
https://maven.apache.org/plugins/maven-dependency-plugin/plugin-info.html

update the plugin version #1362

---

terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/time/JdbcClockFactory.java
terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/time/JdbcClockFactoryTest.java

Modify the processing to take into account the case where queryForObject() returns null. #1396

---

terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/time/JdbcClockFactory.java
terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/time/JdbcClockFactoryTest.java

Modify the processing to take into account the case where queryForObject() returns null. #1396
(cherry picked from commit 44c79bc816dec2084576c413ef6e4867391bfb23)
Please review #1401.

[5.10.x] Modify the processing to take into account the case where queryForObject() returns null.

---

terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/exception/SystemExceptionResolver.java
terasoluna-gfw-parent/pom.xml

Please review #1412.
JCL 1.3 may cause errors in OSS because it is a non-serializable class. Therefore, jcl-over-slf4j is included.
This response is subject to change at a later date.
relates to [TSF4J5-6880](https://terasolunaorg.atlassian.net/browse/TSF4J5-6880).

Apply Spring Boot 4.0.0-M1
